#!/usr/bin/env python3
"""Generate src/db/schema_sql.h from the checked-in schema contract (D01).

The generated header is checked in; production builds never run Python.  Run
from the repository root (or anywhere; paths are resolved from this file):

    python3 tests/db/gen_schema_sql.py

It embeds docs/devel/implementation/contracts/schema.sql byte for byte as the
CF_DB_SCHEMA_SQL macro and records the source path, byte count and SHA-256 in
the header.  No schema changes are generated: the contract is copied exactly.
"""

import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "docs/devel/implementation/contracts/schema.sql"
OUT = ROOT / "src/db/schema_sql.h"


def c_escape(line: str) -> str:
    return line.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    data = CONTRACT.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    text = data.decode("utf-8")
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]

    body = []
    for i, line in enumerate(lines):
        continuation = " \\" if i + 1 < len(lines) else ""
        body.append(f'    "{c_escape(line)}\\n"{continuation}')
    body_text = "\n".join(body)

    header = f"""/* Generated by tests/db/gen_schema_sql.py from the checked-in contract.
 * Do not edit this file by hand; regenerate and commit the result:
 *
 *     python3 tests/db/gen_schema_sql.py
 *
 * Provenance
 * ----------
 * Source:      docs/devel/implementation/contracts/schema.sql
 * Source sha256: {digest}
 * Source bytes:  {len(data)}
 * Generated:   2026-10-04 by task D01 (db-core) from the contract revision
 *               in this checkout.
 *
 * CF_DB_SCHEMA_SQL is the contract byte for byte, including its final
 * `PRAGMA user_version = 1;`.  src/db/schema.c executes it inside one
 * BEGIN IMMEDIATE transaction when it creates a fresh database.
 */
#ifndef CF_DB_SCHEMA_SQL_H
#define CF_DB_SCHEMA_SQL_H

#define CF_DB_SCHEMA_SQL_SOURCE "docs/devel/implementation/contracts/schema.sql"
#define CF_DB_SCHEMA_SQL_SHA256 "{digest}"
#define CF_DB_SCHEMA_SQL_BYTES {len(data)}

#define CF_DB_SCHEMA_SQL \\
{body_text}

#endif /* CF_DB_SCHEMA_SQL_H */
"""

    OUT.write_text(header, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")
    print(f"source sha256 {digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
