# Generates ../../search/word_ranges.rs: the code points Ruby's /[[:word:]]/ matches (Onigmo's
# Unicode tables in the reference's Ruby), as ranges.
#   parity/bin/reference runner crates/campfire/src/integrations/testdata/oracle/search_word.rb
ranges = []
(0..0x10FFFF).each do |cp|
  next if cp.between?(0xD800, 0xDFFF)
  next unless [cp].pack("U").match?(/[[:word:]]/)
  if ranges.any? && ranges.last[1] == cp - 1
    ranges.last[1] = cp
  else
    ranges << [cp, cp]
  end
end
body = ranges.map { |a, b| format("    (0x%X, 0x%X),", a, b) }.join("\n")
File.write(File.expand_path("../../search/word_ranges.rs", __dir__), <<~RUST)
  //! Generated by integrations/testdata/oracle/search_word.rb from Ruby #{RUBY_VERSION}
  //! (Unicode #{RbConfig::CONFIG["UNICODE_VERSION"]}): the code points `/[[:word:]]/` matches.

  pub const WORD_RANGES: &[(u32, u32)] = &[
  #{body}
  ];
RUST
