/* tests/auth/vectors.h — generated by tests/auth/tools/generate_vectors.py.
 * Source: tests/fixtures/vectors/rails_compat.json (current-format selection only;
 * legacy/Marshal vectors are excluded by the fixture manifest, D-C01).
 * Do not edit by hand: rerun the generator. */
#ifndef CF_TESTS_AUTH_VECTORS_H
#define CF_TESTS_AUTH_VECTORS_H

#include <stdbool.h>
#include <stdint.h>

#define AUTH_VEC_SECRET_KEY_BASE "5335c3b1ad35b4ad170c3413bd651ef3b6ed64e257261871a6de3f978cf3868ee417a927040935fb30b0f7debdedb34a2a403e9f34b16cf594c917c2ecd4a995"
#define AUTH_VEC_NOW "2026-01-01T12:00:00.000Z"

typedef struct { const char *salt; unsigned length; const char *key_hex; } auth_vec_key;
static const auth_vec_key AUTH_VEC_KEYS[] = {
    {"signed cookie", 64, "4777669222a1dfbfcb0ae1a07fee1450b0c2aeccc8821f27a4514212906dd3d142608325b7b3126978936f407bb147605a074d6d4a63bb4edd9518d72f4f9399"},
    {"authenticated encrypted cookie", 32, "c37b900eab3de6f1f2c0693db47bcb6d24f11b2668329b978a93aebcf77283c2"},
    {"active_record/signed_id", 64, "d704274602b9061592784bb128b2c8a4695c21158f43d860d6fcd250c3f95f78b2cbd4dd403cffb203eeedb674f4def53d9717d0515ce5dd1e1f93ec65185378"},
    {"signed_global_ids", 64, "8ac0edd7b69e1f16def30fb863b78b0bc21c4f17ae69395b6817638808e472cf5fda07afc057e50cd38bb965a419159e748ad0e69bc0eba01862bf0c36897dad"},
    {"turbo/signed_stream_verifier_key", 64, "52b780d76ae81794bede4c5422bcb016add697bf9e980d711c67c08470330b704dad5cbe0ecf89edf277151ce8f563e45b99b5c7bc9e8e2f574aecce3d27b85a"},
    {"anything", 16, "9d6645a5b0eebc1ac4ee543a165eca9c"},
};
#define AUTH_VEC_KEYS_LEN (sizeof AUTH_VEC_KEYS / sizeof AUTH_VEC_KEYS[0])

typedef struct { const char *name; const char *value; const char *expires_at; const char *raw; const char *set_cookie; } auth_vec_signed_gen;
static const auth_vec_signed_gen AUTH_VEC_SIGNED_GEN[] = {
    {"session_token", "e5XWBGGnEJqiHpVCZzbj6bra", "2046-01-01T12:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314b9", "session_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314b9; path=/; expires=Mon, 01 Jan 2046 12:00:00 GMT; httponly; samesite=lax"},
    {"session_token", "hello world", "2046-01-01T12:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltaGxiR3h2SUhkdmNteGtJZz09IiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--39bc3535e5f45a95eb9b0e682f896d448c372571", "session_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltaGxiR3h2SUhkdmNteGtJZz09IiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0%3D--39bc3535e5f45a95eb9b0e682f896d448c372571; path=/; expires=Mon, 01 Jan 2046 12:00:00 GMT; httponly; samesite=lax"},
    {"session_token", "a+b/c=d", "2046-01-01T12:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltRXJZaTlqUFdRaSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--14a98e6c374607a23387899e3e4deb393e95087a", "session_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltRXJZaTlqUFdRaSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--14a98e6c374607a23387899e3e4deb393e95087a; path=/; expires=Mon, 01 Jan 2046 12:00:00 GMT; httponly; samesite=lax"},
    {"session_token", "<script>&'\"</script>", "2046-01-01T12:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklseDFNREF6WTNOamNtbHdkRngxTURBelpWeDFNREF5TmlkY0lseDFNREF6WXk5elkzSnBjSFJjZFRBd00yVWkiLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ==--29f504b833cf0789baef02f4caee6d202dd1d692", "session_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IklseDFNREF6WTNOamNtbHdkRngxTURBelpWeDFNREF5TmlkY0lseDFNREF6WXk5elkzSnBjSFJjZFRBd00yVWkiLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ%3D%3D--29f504b833cf0789baef02f4caee6d202dd1d692; path=/; expires=Mon, 01 Jan 2046 12:00:00 GMT; httponly; samesite=lax"},
    {"session_token", "\303\251 \303\274n\303\257c\303\270d\303\251 \342\230\203", "2046-01-01T12:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklzT3BJTU84YnNPdlk4TzRaTU9wSU9LWWd5ST0iLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ==--ad0be021bdb2c70f4eac07fc7e60d76d77ef98cf", "session_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IklzT3BJTU84YnNPdlk4TzRaTU9wSU9LWWd5ST0iLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ%3D%3D--ad0be021bdb2c70f4eac07fc7e60d76d77ef98cf; path=/; expires=Mon, 01 Jan 2046 12:00:00 GMT; httponly; samesite=lax"},
    {"session_token", "line\342\200\250sep\342\200\251", "2046-01-01T12:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklteHBibVhpZ0toelpYRGlnS2tpIiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--1920f09ef997c2bc745cd3d7b16feb41fe859e66", "session_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IklteHBibVhpZ0toelpYRGlnS2tpIiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0%3D--1920f09ef997c2bc745cd3d7b16feb41fe859e66; path=/; expires=Mon, 01 Jan 2046 12:00:00 GMT; httponly; samesite=lax"},
    {"session_token", "tab\tnew\nline\001", "2046-01-01T12:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluUmhZbHgwYm1WM1hHNXNhVzVsWEhVd01EQXhJZz09IiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--de03ac62dbae81bcc76ea6e144b8966a77eb4c09", "session_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluUmhZbHgwYm1WM1hHNXNhVzVsWEhVd01EQXhJZz09IiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0%3D--de03ac62dbae81bcc76ea6e144b8966a77eb4c09; path=/; expires=Mon, 01 Jan 2046 12:00:00 GMT; httponly; samesite=lax"},
    {"session_token", "", "2046-01-01T12:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklpST0iLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ==--3627e25b60265fbf281f75fddcdc95d575f26be0", "session_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IklpST0iLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ%3D%3D--3627e25b60265fbf281f75fddcdc95d575f26be0; path=/; expires=Mon, 01 Jan 2046 12:00:00 GMT; httponly; samesite=lax"},
    {"no_expiry", "value", NULL, "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluWmhiSFZsSWc9PSIsImV4cCI6bnVsbCwicHVyIjoiY29va2llLm5vX2V4cGlyeSJ9fQ==--62885ca65121896da2376780e1c14e9644de460a", "no_expiry=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluWmhiSFZsSWc9PSIsImV4cCI6bnVsbCwicHVyIjoiY29va2llLm5vX2V4cGlyeSJ9fQ%3D%3D--62885ca65121896da2376780e1c14e9644de460a; path=/; samesite=lax"},
    {"short", "short-lived", "2026-01-01T13:00:00.000Z", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluTm9iM0owTFd4cGRtVmtJZz09IiwiZXhwIjoiMjAyNi0wMS0wMVQxMzowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNob3J0In19--fabecbe64423539df34d525102bccf2814a0a9cd", "short=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluTm9iM0owTFd4cGRtVmtJZz09IiwiZXhwIjoiMjAyNi0wMS0wMVQxMzowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNob3J0In19--fabecbe64423539df34d525102bccf2814a0a9cd; path=/; expires=Thu, 01 Jan 2026 13:00:00 GMT; samesite=lax"},
};
#define AUTH_VEC_SIGNED_GEN_LEN (sizeof AUTH_VEC_SIGNED_GEN / sizeof AUTH_VEC_SIGNED_GEN[0])

typedef struct { const char *case_name; const char *name; const char *raw; const char *now; bool has_expected; const char *expected; } auth_vec_cookie_verify;
static const auth_vec_cookie_verify AUTH_VEC_SIGNED_VERIFY[] = {
    {"valid session_token \"e5XWBGGnEJqiHpVCZzbj6bra\"", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314b9", "2026-01-01T12:00:00.000Z", true, "e5XWBGGnEJqiHpVCZzbj6bra"},
    {"valid session_token \"hello world\"", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltaGxiR3h2SUhkdmNteGtJZz09IiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--39bc3535e5f45a95eb9b0e682f896d448c372571", "2026-01-01T12:00:00.000Z", true, "hello world"},
    {"valid session_token \"a+b/c=d\"", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltRXJZaTlqUFdRaSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--14a98e6c374607a23387899e3e4deb393e95087a", "2026-01-01T12:00:00.000Z", true, "a+b/c=d"},
    {"valid session_token \"<script>&'\\\"</script>\"", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklseDFNREF6WTNOamNtbHdkRngxTURBelpWeDFNREF5TmlkY0lseDFNREF6WXk5elkzSnBjSFJjZFRBd00yVWkiLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ==--29f504b833cf0789baef02f4caee6d202dd1d692", "2026-01-01T12:00:00.000Z", true, "<script>&'\"</script>"},
    {"valid session_token \"\303\251 \303\274n\303\257c\303\270d\303\251 \342\230\203\"", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklzT3BJTU84YnNPdlk4TzRaTU9wSU9LWWd5ST0iLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ==--ad0be021bdb2c70f4eac07fc7e60d76d77ef98cf", "2026-01-01T12:00:00.000Z", true, "\303\251 \303\274n\303\257c\303\270d\303\251 \342\230\203"},
    {"valid session_token \"line\\u2028sep\\u2029\"", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklteHBibVhpZ0toelpYRGlnS2tpIiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--1920f09ef997c2bc745cd3d7b16feb41fe859e66", "2026-01-01T12:00:00.000Z", true, "line\342\200\250sep\342\200\251"},
    {"valid session_token \"tab\\tnew\\nline\\u0001\"", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluUmhZbHgwYm1WM1hHNXNhVzVsWEhVd01EQXhJZz09IiwiZXhwIjoiMjA0Ni0wMS0wMVQxMjowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--de03ac62dbae81bcc76ea6e144b8966a77eb4c09", "2026-01-01T12:00:00.000Z", true, "tab\tnew\nline\001"},
    {"valid session_token \"\"", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklpST0iLCJleHAiOiIyMDQ2LTAxLTAxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ==--3627e25b60265fbf281f75fddcdc95d575f26be0", "2026-01-01T12:00:00.000Z", true, ""},
    {"valid no_expiry \"value\"", "no_expiry", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluWmhiSFZsSWc9PSIsImV4cCI6bnVsbCwicHVyIjoiY29va2llLm5vX2V4cGlyeSJ9fQ==--62885ca65121896da2376780e1c14e9644de460a", "2026-01-01T12:00:00.000Z", true, "value"},
    {"valid short \"short-lived\"", "short", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluTm9iM0owTFd4cGRtVmtJZz09IiwiZXhwIjoiMjAyNi0wMS0wMVQxMzowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNob3J0In19--fabecbe64423539df34d525102bccf2814a0a9cd", "2026-01-01T12:00:00.000Z", true, "short-lived"},
    {"short-lived before expiry", "short", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluTm9iM0owTFd4cGRtVmtJZz09IiwiZXhwIjoiMjAyNi0wMS0wMVQxMzowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNob3J0In19--fabecbe64423539df34d525102bccf2814a0a9cd", "2026-01-01T12:59:00.000Z", true, "short-lived"},
    {"short-lived at expiry", "short", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluTm9iM0owTFd4cGRtVmtJZz09IiwiZXhwIjoiMjAyNi0wMS0wMVQxMzowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNob3J0In19--fabecbe64423539df34d525102bccf2814a0a9cd", "2026-01-01T13:00:00.000Z", false, NULL},
    {"short-lived after expiry", "short", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluTm9iM0owTFd4cGRtVmtJZz09IiwiZXhwIjoiMjAyNi0wMS0wMVQxMzowMDowMC4wMDBaIiwicHVyIjoiY29va2llLnNob3J0In19--fabecbe64423539df34d525102bccf2814a0a9cd", "2026-01-01T14:00:00.000Z", false, NULL},
    {"permanent just before 20 years", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314b9", "2046-01-01T11:59:59.000Z", true, "e5XWBGGnEJqiHpVCZzbj6bra"},
    {"permanent after 20 years", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314b9", "2046-01-01T12:00:01.000Z", false, NULL},
    {"wrong cookie name", "other_name", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314b9", "2026-01-01T12:00:00.000Z", false, NULL},
    {"tampered digest", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314b0", "2026-01-01T12:00:00.000Z", false, NULL},
    {"tampered payload", "session_token", "AyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314b9", "2026-01-01T12:00:00.000Z", false, NULL},
    {"digest removed", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19", "2026-01-01T12:00:00.000Z", false, NULL},
    {"truncated digest", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--97d26d3a75e1d4d5a12fa3a2448d1feac36314", "2026-01-01T12:00:00.000Z", false, NULL},
    {"garbage", "session_token", "not a cookie", "2026-01-01T12:00:00.000Z", false, NULL},
    {"empty", "session_token", "", "2026-01-01T12:00:00.000Z", false, NULL},
    {"signed with rotated secret", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--4fcf902faaeb60839f956ce1c801ed835fe5a90e", "2026-01-01T12:00:00.000Z", false, NULL},
    {"sha256 digest", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVTFXRmRDUjBkdVJVcHhhVWh3VmtOYWVtSnFObUp5WVNJPSIsImV4cCI6IjIwNDYtMDEtMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--2312d3799228fec2236043730ed5f6ae4de44c6ece7124606536d235ac73d46f", "2026-01-01T12:00:00.000Z", false, NULL},
    {"metadata without purpose", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltNXZjSFZ5Y0c5elpTST0iLCJleHAiOiIyMDI2LTAxLTAyVDEyOjAwOjAwLjAwMFoiLCJwdXIiOm51bGx9fQ==--ce674c4e2eae4763923a1a05d72f6b9fdcdf14fc", "2026-01-01T12:00:00.000Z", true, "nopurpose"},
    {"metadata without purpose, expired", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltNXZjSFZ5Y0c5elpTST0iLCJleHAiOiIyMDI1LTEyLTMxVDEyOjAwOjAwLjAwMFoiLCJwdXIiOm51bGx9fQ==--991b52e0442af6ca5302f80e6fd90b38060f536e", "2026-01-01T12:00:00.000Z", false, NULL},
    {"purpose of another cookie", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluZ2kiLCJleHAiOm51bGwsInB1ciI6ImNvb2tpZS5vdGhlciJ9fQ==--d3cabe684a242043755b350b99d67ad0c3c2a557", "2026-01-01T12:00:00.000Z", false, NULL},
    {"json integer value", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1USXoiLCJleHAiOm51bGwsInB1ciI6ImNvb2tpZS5zZXNzaW9uX3Rva2VuIn19--4e01a2f412b6fff5d82f2e7c18592da31be06786", "2026-01-01T12:00:00.000Z", false, NULL},
    {"json object value", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6ImV5SmhJam94ZlE9PSIsImV4cCI6bnVsbCwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--e72973158fcec6041a61cb6d2889c1f5ff47cf12", "2026-01-01T12:00:00.000Z", false, NULL},
    {"unparseable value", "session_token", "eyJfcmFpbHMiOnsibWVzc2FnZSI6ImJtOTBJR3B6YjI0PSIsImV4cCI6bnVsbCwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--ee079fb585dc2bf67b9026e9497077d7948eda8b", "2026-01-01T12:00:00.000Z", false, NULL},
    {"new-style envelope", "session_token", "eyJfcmFpbHMiOnsiZGF0YSI6IngiLCJwdXIiOiJjb29raWUuc2Vzc2lvbl90b2tlbiJ9fQ==--4ed1f8dd2148962bafc9a10c184e6085af6ea631", "2026-01-01T12:00:00.000Z", false, NULL},
};
#define AUTH_VEC_SIGNED_VERIFY_LEN (sizeof AUTH_VEC_SIGNED_VERIFY / sizeof AUTH_VEC_SIGNED_VERIFY[0])

typedef struct { const char *name; const char *value_json; const char *expires_at; } auth_vec_encrypted_gen;
static const auth_vec_encrypted_gen AUTH_VEC_ENCRYPTED_GEN[] = {
    {"_campfire_session", "{\"session_id\":\"6d3a2b1c0f9e8d7c6b5a493827161504\",\"_csrf_token\":\"qK3zv7cQ2oYlP4-sX6JtW0nBf9eR1uHaMdLgE5iVy8k\"}", "2046-01-01T12:00:00.000Z"},
    {"_campfire_session", "{\"session_id\":\"abc\",\"return_to_after_authenticating\":\"http://campfire.test/rooms/1?a=1&b=<2>\"}", "2046-01-01T12:00:00.000Z"},
    {"_campfire_session", "\"plain string\"", "2046-01-01T12:00:00.000Z"},
    {"_campfire_session", "42", "2046-01-01T12:00:00.000Z"},
    {"_campfire_session", "[1,\"two\",null,true]", "2046-01-01T12:00:00.000Z"},
    {"_campfire_session", "{\"nested\":{\"\303\251\":\"\342\230\203\342\200\250\"}}", "2046-01-01T12:00:00.000Z"},
    {"short", "\"short-lived\"", "2026-01-01T13:00:00.000Z"},
    {"no_expiry", "\"forever\"", NULL},
};
#define AUTH_VEC_ENCRYPTED_GEN_LEN (sizeof AUTH_VEC_ENCRYPTED_GEN / sizeof AUTH_VEC_ENCRYPTED_GEN[0])

typedef struct { const char *case_name; const char *name; const char *raw; const char *now; bool has_expected; const char *expected_json; } auth_vec_encrypted_verify;
static const auth_vec_encrypted_verify AUTH_VEC_ENCRYPTED_VERIFY[] = {
    {"valid _campfire_session {\"session_id\" => \"6d3a2b1c0f9e8d7c6b5a49", "_campfire_session", "NOlqOHTLnofV9OfOPTKwbz37W5h0q5v2MN7NAxU32S858Btw/VEXc0cNPhs9WTp42dlZrAyx8asFgNETEY83jKHTybeGKogaRsHJXG/M9O92ZHdCZg4zFslMfzI2DgBZIyKL3sIesagGeqVNYqRgi/4vc+QA3lX2xTL01kNKc/sKGtt2WXI45za/LQyIy1xHHmfNXpGS7nEswMMw5AXqXk1lC0PKGKd+s8YLD8f+0Tc3dJ9M6hygi2I16zTTRhRCFl5WdKjc0WsmRblgDw+xrYJ5s9NwwuqN/tA8Uom39ma0w+QUh+GBrvR5dueBJK0=--aLsLJQUZe1sHp4Y/--gXqGsSLjvclcSmibYj1XYQ==", "2026-01-01T12:00:00.000Z", true, "{\"session_id\":\"6d3a2b1c0f9e8d7c6b5a493827161504\",\"_csrf_token\":\"qK3zv7cQ2oYlP4-sX6JtW0nBf9eR1uHaMdLgE5iVy8k\"}"},
    {"valid _campfire_session {\"session_id\" => \"abc\", \"return_to_after", "_campfire_session", "Mltp2V+lJUXoHwCPulaV5ovHpQB5PNVEJKG+CYHrFhTZqJ+KZI9yhpYzr9WuGwPh2VXWaSpiRkclC8JmIv9mtIVFXstMSOPlEMB4qawo30mAAu79B9xGKPao7gQCpjgCAnrSoCwWWtVXH3gD52XQpBFhWXzm8a8IPi/vqTdPbHj0pH2JUhqTFX8tPIWHZ7YrnR8tRCTGp5sBxQYNQ1s0Zp94shMON8mJ3ForjWvQsTM/RImFm5KHYfQLqQancp3sFPJKCS8r/jt9rZePAhznqZKoA4oj6KfWy0EbV+XrfsA/RvDnSQgxZ0tVtDDhID0=--mZL/dQUCpZMaYjVh--z/3hFjCLRDe9c4ZSNVlzBA==", "2026-01-01T12:00:00.000Z", true, "{\"session_id\":\"abc\",\"return_to_after_authenticating\":\"http://campfire.test/rooms/1?a=1&b=<2>\"}"},
    {"valid _campfire_session \"plain string\"", "_campfire_session", "vU7zaCPG6QiW7W89JSsuWOJyjmlrc1WxzIa2Ya7Qw32JmirOGOsKF0TzMl1NLmVgv4LKnUqX3vTEimLArNX5P0h6a3O+lB7/nOGhvzQoCMsDElmeNkvCNTy1UacPQ59rDDZeyBOCvT9XL8poOZ79--Ybo+WrUrroQc9u1u--j1IukvrbemySHCiKo8gzbw==", "2026-01-01T12:00:00.000Z", true, "\"plain string\""},
    {"valid _campfire_session 42", "_campfire_session", "M/ROjAT5T8qc4iGsMkb7CWLFyfP0kAd/UE6qTQQxJy7FojbDNDu/KUI78F6ucwTq3o4aIzDWQvn6PnGS8CmQGeWW4p/iXYOR6udzCJPdggQyqavZBOogOPu9rsE2kcc=--CYN80krmllK36gfO--SDWnObmUQbc1kGXOT5Av6g==", "2026-01-01T12:00:00.000Z", true, "42"},
    {"valid _campfire_session [1, \"two\", nil, true]", "_campfire_session", "yje8MLRD8L5xnn4tdpPvbWyeoTs1MBHiN+WjA6hIerGc64kFvu9Gio24gjH+HQsF/+QQ65ArlUxKIFajtzUXTiV5t/m+hLp6Q4yyUpXJ4t6OlTCsNL2i9bJafyUaSzt9MoYBrAGjI7KYY7JeETeqYgoCPMKOndY=--+DFP/t3N4bHPrDuI--AR+CsfVctLYapDJyk5eGWQ==", "2026-01-01T12:00:00.000Z", true, "[1,\"two\",null,true]"},
    {"valid _campfire_session {\"nested\" => {\"\303\251\" => \"\342\230\203\\u2028\"}}", "_campfire_session", "1KPr7vH1dKD4O8S0mPlVNPhS37HqadNrZw1GvE62av1WnbgGzxmcrdeDa4KGp5govkvL9s9r0IjgzYe6sqr3wnoMjZxlfy8nYdlGrl+5PkouY7SmM4MK4oSbtcUbFWDUGjNLXm/OaH9dO8TPmt5dvtj84cHKQK155HOGh/9qrQ==--444jBiwpEptBYPY5--gMYzZ/8/ElbU9GhvzfGbxg==", "2026-01-01T12:00:00.000Z", true, "{\"nested\":{\"\303\251\":\"\342\230\203\342\200\250\"}}"},
    {"valid short \"short-lived\"", "short", "JEK+GZF9xu62Rx6U7zC8Rw0/t9P8Y61uFki4vmUD1NPI4guY+u5cKMI/IlSOH3JKG0LzmFT6mgsQfyFGM1wLzB/KxDdS6wB0VF0Mfdd9ipg4mLICyNKlTSHRKCdJhTj0+Xvp--6idWOtttFR0Iql+N--0Mw3B+FFaaWgJOVBPim9PA==", "2026-01-01T12:00:00.000Z", true, "\"short-lived\""},
    {"valid no_expiry \"forever\"", "no_expiry", "o4Gh+Z5ylxMiVlyivfkdT7MZJgQ/qG5qTUq2IYsYOh+lyspb3LHgSDIt2D8Nm8zsEzMq/6dHlxLif+4HJjHevPgu1A9fW1GXMQ==--bfgPvzTOVpuT9XO2--8gFl+Tl27FsnnxDyd/tWkw==", "2026-01-01T12:00:00.000Z", true, "\"forever\""},
    {"short-lived after expiry", "short", "JEK+GZF9xu62Rx6U7zC8Rw0/t9P8Y61uFki4vmUD1NPI4guY+u5cKMI/IlSOH3JKG0LzmFT6mgsQfyFGM1wLzB/KxDdS6wB0VF0Mfdd9ipg4mLICyNKlTSHRKCdJhTj0+Xvp--6idWOtttFR0Iql+N--0Mw3B+FFaaWgJOVBPim9PA==", "2026-01-01T14:00:00.000Z", false, NULL},
    {"short-lived before expiry", "short", "JEK+GZF9xu62Rx6U7zC8Rw0/t9P8Y61uFki4vmUD1NPI4guY+u5cKMI/IlSOH3JKG0LzmFT6mgsQfyFGM1wLzB/KxDdS6wB0VF0Mfdd9ipg4mLICyNKlTSHRKCdJhTj0+Xvp--6idWOtttFR0Iql+N--0Mw3B+FFaaWgJOVBPim9PA==", "2026-01-01T12:30:00.000Z", true, "\"short-lived\""},
    {"wrong cookie name", "other", "NOlqOHTLnofV9OfOPTKwbz37W5h0q5v2MN7NAxU32S858Btw/VEXc0cNPhs9WTp42dlZrAyx8asFgNETEY83jKHTybeGKogaRsHJXG/M9O92ZHdCZg4zFslMfzI2DgBZIyKL3sIesagGeqVNYqRgi/4vc+QA3lX2xTL01kNKc/sKGtt2WXI45za/LQyIy1xHHmfNXpGS7nEswMMw5AXqXk1lC0PKGKd+s8YLD8f+0Tc3dJ9M6hygi2I16zTTRhRCFl5WdKjc0WsmRblgDw+xrYJ5s9NwwuqN/tA8Uom39ma0w+QUh+GBrvR5dueBJK0=--aLsLJQUZe1sHp4Y/--gXqGsSLjvclcSmibYj1XYQ==", "2026-01-01T12:00:00.000Z", false, NULL},
    {"tampered ciphertext", "_campfire_session", "AOlqOHTLnofV9OfOPTKwbz37W5h0q5v2MN7NAxU32S858Btw/VEXc0cNPhs9WTp42dlZrAyx8asFgNETEY83jKHTybeGKogaRsHJXG/M9O92ZHdCZg4zFslMfzI2DgBZIyKL3sIesagGeqVNYqRgi/4vc+QA3lX2xTL01kNKc/sKGtt2WXI45za/LQyIy1xHHmfNXpGS7nEswMMw5AXqXk1lC0PKGKd+s8YLD8f+0Tc3dJ9M6hygi2I16zTTRhRCFl5WdKjc0WsmRblgDw+xrYJ5s9NwwuqN/tA8Uom39ma0w+QUh+GBrvR5dueBJK0=--aLsLJQUZe1sHp4Y/--gXqGsSLjvclcSmibYj1XYQ==", "2026-01-01T12:00:00.000Z", false, NULL},
    {"tampered iv", "_campfire_session", "NOlqOHTLnofV9OfOPTKwbz37W5h0q5v2MN7NAxU32S858Btw/VEXc0cNPhs9WTp42dlZrAyx8asFgNETEY83jKHTybeGKogaRsHJXG/M9O92ZHdCZg4zFslMfzI2DgBZIyKL3sIesagGeqVNYqRgi/4vc+QA3lX2xTL01kNKc/sKGtt2WXI45za/LQyIy1xHHmfNXpGS7nEswMMw5AXqXk1lC0PKGKd+s8YLD8f+0Tc3dJ9M6hygi2I16zTTRhRCFl5WdKjc0WsmRblgDw+xrYJ5s9NwwuqN/tA8Uom39ma0w+QUh+GBrvR5dueBJK0=--ALsLJQUZe1sHp4Y/--gXqGsSLjvclcSmibYj1XYQ==", "2026-01-01T12:00:00.000Z", false, NULL},
    {"tampered auth tag", "_campfire_session", "NOlqOHTLnofV9OfOPTKwbz37W5h0q5v2MN7NAxU32S858Btw/VEXc0cNPhs9WTp42dlZrAyx8asFgNETEY83jKHTybeGKogaRsHJXG/M9O92ZHdCZg4zFslMfzI2DgBZIyKL3sIesagGeqVNYqRgi/4vc+QA3lX2xTL01kNKc/sKGtt2WXI45za/LQyIy1xHHmfNXpGS7nEswMMw5AXqXk1lC0PKGKd+s8YLD8f+0Tc3dJ9M6hygi2I16zTTRhRCFl5WdKjc0WsmRblgDw+xrYJ5s9NwwuqN/tA8Uom39ma0w+QUh+GBrvR5dueBJK0=--aLsLJQUZe1sHp4Y/--AXqGsSLjvclcSmibYj1XYQ==", "2026-01-01T12:00:00.000Z", false, NULL},
    {"missing auth tag", "_campfire_session", "NOlqOHTLnofV9OfOPTKwbz37W5h0q5v2MN7NAxU32S858Btw/VEXc0cNPhs9WTp42dlZrAyx8asFgNETEY83jKHTybeGKogaRsHJXG/M9O92ZHdCZg4zFslMfzI2DgBZIyKL3sIesagGeqVNYqRgi/4vc+QA3lX2xTL01kNKc/sKGtt2WXI45za/LQyIy1xHHmfNXpGS7nEswMMw5AXqXk1lC0PKGKd+s8YLD8f+0Tc3dJ9M6hygi2I16zTTRhRCFl5WdKjc0WsmRblgDw+xrYJ5s9NwwuqN/tA8Uom39ma0w+QUh+GBrvR5dueBJK0=--aLsLJQUZe1sHp4Y/", "2026-01-01T12:00:00.000Z", false, NULL},
    {"truncated auth tag", "_campfire_session", "NOlqOHTLnofV9OfOPTKwbz37W5h0q5v2MN7NAxU32S858Btw/VEXc0cNPhs9WTp42dlZrAyx8asFgNETEY83jKHTybeGKogaRsHJXG/M9O92ZHdCZg4zFslMfzI2DgBZIyKL3sIesagGeqVNYqRgi/4vc+QA3lX2xTL01kNKc/sKGtt2WXI45za/LQyIy1xHHmfNXpGS7nEswMMw5AXqXk1lC0PKGKd+s8YLD8f+0Tc3dJ9M6hygi2I16zTTRhRCFl5WdKjc0WsmRblgDw+xrYJ5s9NwwuqN/tA8Uom39ma0w+QUh+GBrvR5dueBJK0=--aLsLJQUZe1sHp4Y/--gXqGsSLjvclc", "2026-01-01T12:00:00.000Z", false, NULL},
    {"garbage", "_campfire_session", "garbage", "2026-01-01T12:00:00.000Z", false, NULL},
    {"encrypted with rotated secret", "_campfire_session", "+66V5tUc5niERMQqM2AOBXiFDtXV1JHO9S6ymsJVDViMQHXd0fq4h/qaG3uY8GaTc2tevyiBGxq//RYqctxKxSHtC+iqs6Zb2XGo8iYw01mZPUKlEsX1+h4ZowlCHzl2fGrau8rV5hy9Zm4arMXFiSx9BFABq3PT9TOOHVNMiotRVQhU6mtQSUE8JnBmv9vuOVgZZYdmQNPSdX8/iUv4mv8q/a+1b1+7cMOn6LjH69ouA/IQ/9zQ9oa9Yu31FWIxwEodQnTyTwvRmczXqrODBRrICR70aibFnAfkAK0XvAkOU4dL3/gFRAcqchNWy/Y=--pEv/SH8/9TBxUU3w--oUodO6tMn1ksPsdGwxICbA==", "2026-01-01T12:00:00.000Z", false, NULL},
};
#define AUTH_VEC_ENCRYPTED_VERIFY_LEN (sizeof AUTH_VEC_ENCRYPTED_VERIFY / sizeof AUTH_VEC_ENCRYPTED_VERIFY[0])

typedef struct { const char *model; int64_t id; const char *purpose; const char *expires_at; const char *signed_id; } auth_vec_sid_gen;
static const auth_vec_sid_gen AUTH_VEC_SID_GEN[] = {
    {"User", 1, "avatar", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e1"},
    {"User", 1, "transfer", "2026-01-01T16:00:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6MSwiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--84b6cbc2d8ed3a38eca9044b3791b20d41abb332c2f81c01fc13a1534d4dc3a6"},
    {"User", 1, NULL, NULL, "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlciJ9fQ--ca0a5ac7b8763056751763399933da27f8551acad70d40c9be532b8b31e16c1b"},
    {"User", 2, "avatar", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6MiwicHVyIjoidXNlci9hdmF0YXIifX0--18b8839b6557c9efbe30c5aa140bd88b7b723b705167ec563f69e2522adb22b3"},
    {"User", 2, "transfer", "2026-01-01T16:00:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6MiwiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--bdd9bea926e971fe9d119dbd22f2cd054d55f858f9fcd85ebacb9f3fe6a0706d"},
    {"User", 2, NULL, NULL, "eyJfcmFpbHMiOnsiZGF0YSI6MiwicHVyIjoidXNlciJ9fQ--7e6a28967b4f7466e2a67a8533ad3e7f83adc814f9c356251d4c337db5b0ac80"},
    {"User", 12345, "avatar", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6MTIzNDUsInB1ciI6InVzZXIvYXZhdGFyIn19--169ed9d46dc6dfbed888ed5e8add66e3f16fb61e4764c104a900aaf82fcaaaa2"},
    {"User", 12345, "transfer", "2026-01-01T16:00:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6MTIzNDUsImV4cCI6IjIwMjYtMDEtMDFUMTY6MDA6MDAuMDAwWiIsInB1ciI6InVzZXIvdHJhbnNmZXIifX0--908466b7bdffa61056af41b8d4f464b5b99f9c479ea973d7869b5dfb2eb3864a"},
    {"User", 12345, NULL, NULL, "eyJfcmFpbHMiOnsiZGF0YSI6MTIzNDUsInB1ciI6InVzZXIifX0--7c85dd0b655d8729be00bd7da6e8d37589ca13f7360608a36cb04c6d8bb5bbea"},
    {"User", 9007199254740993, "avatar", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6OTAwNzE5OTI1NDc0MDk5MywicHVyIjoidXNlci9hdmF0YXIifX0--25760de52cfbcdcb439e0ff1fddb721fbd7c67499ed4a7fb5e2fc4616fea3457"},
    {"User", 9007199254740993, "transfer", "2026-01-01T16:00:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6OTAwNzE5OTI1NDc0MDk5MywiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--d6d7efab76468e826f5c93957a3289820d2f2357076e24e1f47d1dd5819d31ae"},
    {"User", 9007199254740993, NULL, NULL, "eyJfcmFpbHMiOnsiZGF0YSI6OTAwNzE5OTI1NDc0MDk5MywicHVyIjoidXNlciJ9fQ--d0532c404c6372acc706b334bd9f7307eefeebf13ab97c80165eccbeaebc983d"},
    {"Room", 1, "avatar", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoicm9vbS9hdmF0YXIifX0--57f4ae85db0114da3e1a05f74877f24805e20f29f85e65e0f4e5df7a8545a04c"},
    {"User", 1, "transfer", "2026-01-01T12:30:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6MSwiZXhwIjoiMjAyNi0wMS0wMVQxMjozMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--cd31c899f438aeaad22214b4ca0465affd1b10d4d403105137923123610d9e0d"},
};
#define AUTH_VEC_SID_GEN_LEN (sizeof AUTH_VEC_SID_GEN / sizeof AUTH_VEC_SID_GEN[0])

typedef struct { const char *case_name; const char *model; const char *signed_id; const char *purpose; const char *now; bool has_expected; int64_t expected; } auth_vec_sid_verify;
static const auth_vec_sid_verify AUTH_VEC_SID_VERIFY[] = {
    {"valid User 1 avatar", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e1", "avatar", "2026-01-01T12:00:00.000Z", true, 1},
    {"valid User 1 transfer", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--84b6cbc2d8ed3a38eca9044b3791b20d41abb332c2f81c01fc13a1534d4dc3a6", "transfer", "2026-01-01T12:00:00.000Z", true, 1},
    {"valid User 1 ", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlciJ9fQ--ca0a5ac7b8763056751763399933da27f8551acad70d40c9be532b8b31e16c1b", NULL, "2026-01-01T12:00:00.000Z", true, 1},
    {"valid User 2 avatar", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MiwicHVyIjoidXNlci9hdmF0YXIifX0--18b8839b6557c9efbe30c5aa140bd88b7b723b705167ec563f69e2522adb22b3", "avatar", "2026-01-01T12:00:00.000Z", true, 2},
    {"valid User 2 transfer", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MiwiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--bdd9bea926e971fe9d119dbd22f2cd054d55f858f9fcd85ebacb9f3fe6a0706d", "transfer", "2026-01-01T12:00:00.000Z", true, 2},
    {"valid User 2 ", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MiwicHVyIjoidXNlciJ9fQ--7e6a28967b4f7466e2a67a8533ad3e7f83adc814f9c356251d4c337db5b0ac80", NULL, "2026-01-01T12:00:00.000Z", true, 2},
    {"valid User 12345 avatar", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MTIzNDUsInB1ciI6InVzZXIvYXZhdGFyIn19--169ed9d46dc6dfbed888ed5e8add66e3f16fb61e4764c104a900aaf82fcaaaa2", "avatar", "2026-01-01T12:00:00.000Z", true, 12345},
    {"valid User 12345 transfer", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MTIzNDUsImV4cCI6IjIwMjYtMDEtMDFUMTY6MDA6MDAuMDAwWiIsInB1ciI6InVzZXIvdHJhbnNmZXIifX0--908466b7bdffa61056af41b8d4f464b5b99f9c479ea973d7869b5dfb2eb3864a", "transfer", "2026-01-01T12:00:00.000Z", true, 12345},
    {"valid User 12345 ", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MTIzNDUsInB1ciI6InVzZXIifX0--7c85dd0b655d8729be00bd7da6e8d37589ca13f7360608a36cb04c6d8bb5bbea", NULL, "2026-01-01T12:00:00.000Z", true, 12345},
    {"valid User 9007199254740993 avatar", "User", "eyJfcmFpbHMiOnsiZGF0YSI6OTAwNzE5OTI1NDc0MDk5MywicHVyIjoidXNlci9hdmF0YXIifX0--25760de52cfbcdcb439e0ff1fddb721fbd7c67499ed4a7fb5e2fc4616fea3457", "avatar", "2026-01-01T12:00:00.000Z", true, 9007199254740993},
    {"valid User 9007199254740993 transfer", "User", "eyJfcmFpbHMiOnsiZGF0YSI6OTAwNzE5OTI1NDc0MDk5MywiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--d6d7efab76468e826f5c93957a3289820d2f2357076e24e1f47d1dd5819d31ae", "transfer", "2026-01-01T12:00:00.000Z", true, 9007199254740993},
    {"valid User 9007199254740993 ", "User", "eyJfcmFpbHMiOnsiZGF0YSI6OTAwNzE5OTI1NDc0MDk5MywicHVyIjoidXNlciJ9fQ--d0532c404c6372acc706b334bd9f7307eefeebf13ab97c80165eccbeaebc983d", NULL, "2026-01-01T12:00:00.000Z", true, 9007199254740993},
    {"valid Room 1 avatar", "Room", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoicm9vbS9hdmF0YXIifX0--57f4ae85db0114da3e1a05f74877f24805e20f29f85e65e0f4e5df7a8545a04c", "avatar", "2026-01-01T12:00:00.000Z", true, 1},
    {"valid User 1 transfer", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwiZXhwIjoiMjAyNi0wMS0wMVQxMjozMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--cd31c899f438aeaad22214b4ca0465affd1b10d4d403105137923123610d9e0d", "transfer", "2026-01-01T12:00:00.000Z", true, 1},
    {"transfer before expiry", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--84b6cbc2d8ed3a38eca9044b3791b20d41abb332c2f81c01fc13a1534d4dc3a6", "transfer", "2026-01-01T15:59:59.000Z", true, 1},
    {"transfer at expiry", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--84b6cbc2d8ed3a38eca9044b3791b20d41abb332c2f81c01fc13a1534d4dc3a6", "transfer", "2026-01-01T16:00:00.000Z", false, 0},
    {"transfer after expiry", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwiZXhwIjoiMjAyNi0wMS0wMVQxNjowMDowMC4wMDBaIiwicHVyIjoidXNlci90cmFuc2ZlciJ9fQ--84b6cbc2d8ed3a38eca9044b3791b20d41abb332c2f81c01fc13a1534d4dc3a6", "transfer", "2026-01-01T17:00:00.000Z", false, 0},
    {"avatar far in the future", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e1", "avatar", "2076-01-01T12:00:00.000Z", true, 1},
    {"avatar id used as transfer", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e1", "transfer", "2026-01-01T12:00:00.000Z", false, 0},
    {"avatar id without purpose", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e1", NULL, "2026-01-01T12:00:00.000Z", false, 0},
    {"room avatar id verified as user", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoicm9vbS9hdmF0YXIifX0--57f4ae85db0114da3e1a05f74877f24805e20f29f85e65e0f4e5df7a8545a04c", "avatar", "2026-01-01T12:00:00.000Z", false, 0},
    {"user avatar id verified as room", "Room", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e1", "avatar", "2026-01-01T12:00:00.000Z", false, 0},
    {"tampered digest", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e0", "avatar", "2026-01-01T12:00:00.000Z", false, 0},
    {"tampered payload", "User", "AyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e1", "avatar", "2026-01-01T12:00:00.000Z", false, 0},
    {"signed with rotated secret", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--3b1f4b420b87794f37a9492df70dba226d014f1fc0d39091b785b92533de6c97", "avatar", "2026-01-01T12:00:00.000Z", false, 0},
    {"garbage", "User", "garbage", "avatar", "2026-01-01T12:00:00.000Z", false, 0},
    {"empty", "User", "", "avatar", "2026-01-01T12:00:00.000Z", false, 0},
    {"standard base64 of url-safe message", "User", "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0=--f0d1d41d37df76165d87a0be1be782aace5037b03146a72f5b4303b825f3470e", "avatar", "2026-01-01T12:00:00.000Z", true, 1},
    {"string id", "User", "eyJfcmFpbHMiOnsiZGF0YSI6IjciLCJwdXIiOiJ1c2VyL2F2YXRhciJ9fQ--fc248b0d4e94a913880767c1b0b95bfe71ce692372e175f7931ff31461ba7045", "avatar", "2026-01-01T12:00:00.000Z", true, 7},
};
#define AUTH_VEC_SID_VERIFY_LEN (sizeof AUTH_VEC_SID_VERIFY / sizeof AUTH_VEC_SID_VERIFY[0])

typedef struct { const char *gid; const char *data; const char *purpose; const char *expires_at; const char *sgid; } auth_vec_sgid_gen;
static const auth_vec_sgid_gen AUTH_VEC_SGID_GEN[] = {
    {"gid://campfire/User/1", "gid://campfire/User/1?expires_in", "attachable", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--f7d8e8773314d3310320f3cdd08e5597bb51ca1a"},
    {"gid://campfire/User/2", "gid://campfire/User/2?expires_in", "attachable", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMj9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--1ba63351f035908684be7963e1e62c732d48ec95"},
    {"gid://campfire/Rooms::Open/1", "gid://campfire/Rooms::Open/1?expires_in", "attachable", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1Jvb21zOjpPcGVuLzE_ZXhwaXJlc19pbiIsInB1ciI6ImF0dGFjaGFibGUifX0=--50e71d14f604feee38fecd887de7718e6470d932"},
    {"gid://campfire/User/1", "gid://campfire/User/1", "default", "2026-02-01T12:00:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMSIsImV4cCI6IjIwMjYtMDItMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImRlZmF1bHQifX0=--5b1f86d74b11dd07db1054e1e224f4f7821faa12"},
    {"gid://campfire/User/1", "gid://campfire/User/1", "attachable", "2026-01-01T13:00:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMSIsImV4cCI6IjIwMjYtMDEtMDFUMTM6MDA6MDAuMDAwWiIsInB1ciI6ImF0dGFjaGFibGUifX0=--6bf1671f3bd9117f7eb41d18fa80973969e20d54"},
};
#define AUTH_VEC_SGID_GEN_LEN (sizeof AUTH_VEC_SGID_GEN / sizeof AUTH_VEC_SGID_GEN[0])

typedef struct { const char *case_name; const char *sgid; const char *purpose; const char *now; bool has_expected; const char *expected_gid; } auth_vec_sgid_verify;
static const auth_vec_sgid_verify AUTH_VEC_SGID_VERIFY[] = {
    {"valid gid://campfire/User/1 for attachable", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--f7d8e8773314d3310320f3cdd08e5597bb51ca1a", "attachable", "2026-01-01T12:00:00.000Z", true, "gid://campfire/User/1"},
    {"valid gid://campfire/User/2 for attachable", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMj9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--1ba63351f035908684be7963e1e62c732d48ec95", "attachable", "2026-01-01T12:00:00.000Z", true, "gid://campfire/User/2"},
    {"valid gid://campfire/Rooms::Open/1 for attachable", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1Jvb21zOjpPcGVuLzE_ZXhwaXJlc19pbiIsInB1ciI6ImF0dGFjaGFibGUifX0=--50e71d14f604feee38fecd887de7718e6470d932", "attachable", "2026-01-01T12:00:00.000Z", true, "gid://campfire/Rooms::Open/1"},
    {"valid gid://campfire/User/1 for default", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMSIsImV4cCI6IjIwMjYtMDItMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImRlZmF1bHQifX0=--5b1f86d74b11dd07db1054e1e224f4f7821faa12", "default", "2026-01-01T12:00:00.000Z", true, "gid://campfire/User/1"},
    {"valid gid://campfire/User/1 for attachable", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMSIsImV4cCI6IjIwMjYtMDEtMDFUMTM6MDA6MDAuMDAwWiIsInB1ciI6ImF0dGFjaGFibGUifX0=--6bf1671f3bd9117f7eb41d18fa80973969e20d54", "attachable", "2026-01-01T12:00:00.000Z", true, "gid://campfire/User/1"},
    {"wrong purpose", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--f7d8e8773314d3310320f3cdd08e5597bb51ca1a", "default", "2026-01-01T12:00:00.000Z", false, NULL},
    {"attachable sgid far in the future", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--f7d8e8773314d3310320f3cdd08e5597bb51ca1a", "attachable", "2076-01-01T12:00:00.000Z", true, "gid://campfire/User/1"},
    {"short-lived before expiry", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMSIsImV4cCI6IjIwMjYtMDEtMDFUMTM6MDA6MDAuMDAwWiIsInB1ciI6ImF0dGFjaGFibGUifX0=--6bf1671f3bd9117f7eb41d18fa80973969e20d54", "attachable", "2026-01-01T12:59:00.000Z", true, "gid://campfire/User/1"},
    {"short-lived after expiry", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMSIsImV4cCI6IjIwMjYtMDEtMDFUMTM6MDA6MDAuMDAwWiIsInB1ciI6ImF0dGFjaGFibGUifX0=--6bf1671f3bd9117f7eb41d18fa80973969e20d54", "attachable", "2026-01-01T14:00:00.000Z", false, NULL},
    {"default purpose after a month", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMSIsImV4cCI6IjIwMjYtMDItMDFUMTI6MDA6MDAuMDAwWiIsInB1ciI6ImRlZmF1bHQifX0=--5b1f86d74b11dd07db1054e1e224f4f7821faa12", "default", "2026-02-01T12:00:01.000Z", false, NULL},
    {"tampered digest", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--f7d8e8773314d3310320f3cdd08e5597bb51ca10", "attachable", "2026-01-01T12:00:00.000Z", false, NULL},
    {"tampered payload", "AyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--f7d8e8773314d3310320f3cdd08e5597bb51ca1a", "attachable", "2026-01-01T12:00:00.000Z", false, NULL},
    {"signed with rotated secret", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMSIsInB1ciI6ImF0dGFjaGFibGUifX0=--2163dc554b77f6ff7acb3e73bf8338c950c9ad21", "attachable", "2026-01-01T12:00:00.000Z", false, NULL},
    {"garbage", "garbage", "attachable", "2026-01-01T12:00:00.000Z", false, NULL},
    {"unpadded url-safe base64", "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ--12e2dfc4e593d2f388e28b6f62836d13132d85e7", "attachable", "2026-01-01T12:00:00.000Z", true, "gid://campfire/User/1"},
};
#define AUTH_VEC_SGID_VERIFY_LEN (sizeof AUTH_VEC_SGID_VERIFY / sizeof AUTH_VEC_SGID_VERIFY[0])

typedef struct { const char *parts[8]; size_t parts_len; const char *stream_name; const char *signed_name; } auth_vec_turbo_gen;
static const auth_vec_turbo_gen AUTH_VEC_TURBO_GEN[] = {
    {{"Z2lkOi8vY2FtcGZpcmUvUm9vbXM6Ok9wZW4vMQ", "messages"}, 2, "Z2lkOi8vY2FtcGZpcmUvUm9vbXM6Ok9wZW4vMQ:messages", "IloybGtPaTh2WTJGdGNHWnBjbVV2VW05dmJYTTZPazl3Wlc0dk1ROm1lc3NhZ2VzIg==--6ff497f9ec2f68f7ec64a5aee2fe25bd5ca8e2647ff82db8e211aabd83382b8b"},
    {{"rooms"}, 1, "rooms", "InJvb21zIg==--60a2ff565fb2226042c779b5711156db1d1cc48f89e6f59c94e4bf1da3f0945c"},
    {{"Z2lkOi8vY2FtcGZpcmUvVXNlci8x", "rooms"}, 2, "Z2lkOi8vY2FtcGZpcmUvVXNlci8x:rooms", "IloybGtPaTh2WTJGdGNHWnBjbVV2VlhObGNpOHg6cm9vbXMi--1cc07be3a8b410a4bbfe4ca0988a833987c1c5000f804159f99177c56f9515f8"},
    {{"Z2lkOi8vY2FtcGZpcmUvVXNlci8x"}, 1, "Z2lkOi8vY2FtcGZpcmUvVXNlci8x", "IloybGtPaTh2WTJGdGNHWnBjbVV2VlhObGNpOHgi--ed25739a1c510b640a6e203a6d0303368639e943b45294a9d8d62cc66efb1873"},
    {{"unicode \342\230\203 <&>"}, 1, "unicode \342\230\203 <&>", "InVuaWNvZGUg4piDIDwmPiI=--075667747bb80d01e60af41e6adfe78248ef12c70936b037af197a7584eda21b"},
    {{"a", "b:c"}, 2, "a:b:c", "ImE6YjpjIg==--d65ed5bf97ca33601d27f7cc9bf1c01d7318ec8f2220584c424b7cccfbe3bc20"},
};
#define AUTH_VEC_TURBO_GEN_LEN (sizeof AUTH_VEC_TURBO_GEN / sizeof AUTH_VEC_TURBO_GEN[0])

typedef struct { const char *case_name; const char *signed_name; bool has_expected; const char *expected; } auth_vec_turbo_verify;
static const auth_vec_turbo_verify AUTH_VEC_TURBO_VERIFY[] = {
    {"valid Z2lkOi8vY2FtcGZpcmUvUm9vbXM6Ok9wZW4vMQ:messages", "IloybGtPaTh2WTJGdGNHWnBjbVV2VW05dmJYTTZPazl3Wlc0dk1ROm1lc3NhZ2VzIg==--6ff497f9ec2f68f7ec64a5aee2fe25bd5ca8e2647ff82db8e211aabd83382b8b", true, "Z2lkOi8vY2FtcGZpcmUvUm9vbXM6Ok9wZW4vMQ:messages"},
    {"valid rooms", "InJvb21zIg==--60a2ff565fb2226042c779b5711156db1d1cc48f89e6f59c94e4bf1da3f0945c", true, "rooms"},
    {"valid Z2lkOi8vY2FtcGZpcmUvVXNlci8x:rooms", "IloybGtPaTh2WTJGdGNHWnBjbVV2VlhObGNpOHg6cm9vbXMi--1cc07be3a8b410a4bbfe4ca0988a833987c1c5000f804159f99177c56f9515f8", true, "Z2lkOi8vY2FtcGZpcmUvVXNlci8x:rooms"},
    {"valid Z2lkOi8vY2FtcGZpcmUvVXNlci8x", "IloybGtPaTh2WTJGdGNHWnBjbVV2VlhObGNpOHgi--ed25739a1c510b640a6e203a6d0303368639e943b45294a9d8d62cc66efb1873", true, "Z2lkOi8vY2FtcGZpcmUvVXNlci8x"},
    {"valid unicode \342\230\203 <&>", "InVuaWNvZGUg4piDIDwmPiI=--075667747bb80d01e60af41e6adfe78248ef12c70936b037af197a7584eda21b", true, "unicode \342\230\203 <&>"},
    {"valid a:b:c", "ImE6YjpjIg==--d65ed5bf97ca33601d27f7cc9bf1c01d7318ec8f2220584c424b7cccfbe3bc20", true, "a:b:c"},
    {"tampered digest", "IloybGtPaTh2WTJGdGNHWnBjbVV2VW05dmJYTTZPazl3Wlc0dk1ROm1lc3NhZ2VzIg==--6ff497f9ec2f68f7ec64a5aee2fe25bd5ca8e2647ff82db8e211aabd83382b80", false, NULL},
    {"tampered payload", "AloybGtPaTh2WTJGdGNHWnBjbVV2VW05dmJYTTZPazl3Wlc0dk1ROm1lc3NhZ2VzIg==--6ff497f9ec2f68f7ec64a5aee2fe25bd5ca8e2647ff82db8e211aabd83382b8b", false, NULL},
    {"signed with rotated secret", "InJvb21zIg==--fb7a8f45d793f0970e5e570387bfa0b76dfab784bcbc5ad650b062d39a67ef02", false, NULL},
    {"garbage", "garbage", false, NULL},
    {"with purpose metadata", "eyJfcmFpbHMiOnsiZGF0YSI6InJvb21zIiwicHVyIjoieCJ9fQ==--0e8621b1eccb70339156afafadd4bbc3d8a7f90ba5d7d39531b241634dee9c4d", false, NULL},
    {"json non-string", "NDI=--1e2d201a41131403cad0032a4744939daac57dab9695a576ae74ddee0e9d477f", true, "42"},
};
#define AUTH_VEC_TURBO_VERIFY_LEN (sizeof AUTH_VEC_TURBO_VERIFY / sizeof AUTH_VEC_TURBO_VERIFY[0])

typedef struct { const char *name; const char *data_json; const char *purpose; const char *expires_at; const char *message; } auth_vec_app_gen;
static const auth_vec_app_gen AUTH_VEC_APP_GEN[] = {
    {"ActiveStorage", "42", "blob_id", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--c252dc1b14dd0e8cd599eb40203378880bafed1f"},
    {"ActiveStorage", "9007199254740993", "blob_id", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6OTAwNzE5OTI1NDc0MDk5MywicHVyIjoiYmxvYl9pZCJ9fQ==--67d16c27fcbbe505dc8568bda736787eb3624cb0"},
    {"ActiveStorage", "{\"key\":\"xtapjjcjiudrlk3tmwyjgpuobabd\",\"disposition\":\"inline; filename=\\\"a\\u0026b.png\\\"; filename*=UTF-8''a%26b.png\",\"content_type\":\"image/png\",\"service_name\":\"local\"}", "blob_key", "2026-01-01T12:05:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJ4dGFwampjaml1ZHJsazN0bXd5amdwdW9iYWJkIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwiYVx1MDAyNmIucG5nXCI7IGZpbGVuYW1lKj1VVEYtOCcnYSUyNmIucG5nIiwiY29udGVudF90eXBlIjoiaW1hZ2UvcG5nIiwic2VydmljZV9uYW1lIjoibG9jYWwifSwiZXhwIjoiMjAyNi0wMS0wMVQxMjowNTowMC4wMDBaIiwicHVyIjoiYmxvYl9rZXkifX0=--764195902735b3201f5cf6129ff3b5089150e3e1"},
    {"ActiveStorage", "{\"key\":\"k\",\"content_type\":\"text/plain\",\"content_length\":12,\"checksum\":\"abc==\",\"service_name\":\"local\"}", "blob_token", "2026-01-01T12:05:00.000Z", "eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJrIiwiY29udGVudF90eXBlIjoidGV4dC9wbGFpbiIsImNvbnRlbnRfbGVuZ3RoIjoxMiwiY2hlY2tzdW0iOiJhYmM9PSIsInNlcnZpY2VfbmFtZSI6ImxvY2FsIn0sImV4cCI6IjIwMjYtMDEtMDFUMTI6MDU6MDAuMDAwWiIsInB1ciI6ImJsb2JfdG9rZW4ifX0=--fc9c359d9a82afb6ad1f7cbb5c2056c05eb12081"},
    {"ActiveStorage", "\"0123abc\"", "variation", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6IjAxMjNhYmMiLCJwdXIiOiJ2YXJpYXRpb24ifX0=--a7fae304e60ae716c5ff86c403cbdf5caa286719"},
    {"ActiveStorage", "\"no purpose\"", NULL, NULL, "Im5vIHB1cnBvc2Ui--e731d4394a5529e3d27f6226ed3fe612cf01c1e1"},
    {"something else", "{\"b\":1,\"a\":[\"\\u003c\\u0026\\u003e\"]}", "x", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6eyJiIjoxLCJhIjpbIlx1MDAzY1x1MDAyNlx1MDAzZSJdfSwicHVyIjoieCJ9fQ==--7ff86fef5fdbb102ede55845c3d0fb825b5672c5"},
    {"ActiveStorage", "42", "blob_id", NULL, "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--c252dc1b14dd0e8cd599eb40203378880bafed1f"},
};
#define AUTH_VEC_APP_GEN_LEN (sizeof AUTH_VEC_APP_GEN / sizeof AUTH_VEC_APP_GEN[0])

typedef struct { const char *case_name; const char *name; const char *message; const char *purpose; const char *now; bool has_expected; const char *expected_json; } auth_vec_app_verify;
static const auth_vec_app_verify AUTH_VEC_APP_VERIFY[] = {
    {"valid ActiveStorage blob_id", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--c252dc1b14dd0e8cd599eb40203378880bafed1f", "blob_id", "2026-01-01T12:00:00.000Z", true, "42"},
    {"valid ActiveStorage blob_id", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6OTAwNzE5OTI1NDc0MDk5MywicHVyIjoiYmxvYl9pZCJ9fQ==--67d16c27fcbbe505dc8568bda736787eb3624cb0", "blob_id", "2026-01-01T12:00:00.000Z", true, "9007199254740993"},
    {"valid ActiveStorage blob_key", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJ4dGFwampjaml1ZHJsazN0bXd5amdwdW9iYWJkIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwiYVx1MDAyNmIucG5nXCI7IGZpbGVuYW1lKj1VVEYtOCcnYSUyNmIucG5nIiwiY29udGVudF90eXBlIjoiaW1hZ2UvcG5nIiwic2VydmljZV9uYW1lIjoibG9jYWwifSwiZXhwIjoiMjAyNi0wMS0wMVQxMjowNTowMC4wMDBaIiwicHVyIjoiYmxvYl9rZXkifX0=--764195902735b3201f5cf6129ff3b5089150e3e1", "blob_key", "2026-01-01T12:00:00.000Z", true, "{\"key\":\"xtapjjcjiudrlk3tmwyjgpuobabd\",\"disposition\":\"inline; filename=\\\"a\\u0026b.png\\\"; filename*=UTF-8''a%26b.png\",\"content_type\":\"image/png\",\"service_name\":\"local\"}"},
    {"valid ActiveStorage blob_token", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJrIiwiY29udGVudF90eXBlIjoidGV4dC9wbGFpbiIsImNvbnRlbnRfbGVuZ3RoIjoxMiwiY2hlY2tzdW0iOiJhYmM9PSIsInNlcnZpY2VfbmFtZSI6ImxvY2FsIn0sImV4cCI6IjIwMjYtMDEtMDFUMTI6MDU6MDAuMDAwWiIsInB1ciI6ImJsb2JfdG9rZW4ifX0=--fc9c359d9a82afb6ad1f7cbb5c2056c05eb12081", "blob_token", "2026-01-01T12:00:00.000Z", true, "{\"key\":\"k\",\"content_type\":\"text/plain\",\"content_length\":12,\"checksum\":\"abc==\",\"service_name\":\"local\"}"},
    {"valid ActiveStorage variation", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6IjAxMjNhYmMiLCJwdXIiOiJ2YXJpYXRpb24ifX0=--a7fae304e60ae716c5ff86c403cbdf5caa286719", "variation", "2026-01-01T12:00:00.000Z", true, "\"0123abc\""},
    {"valid ActiveStorage ", "ActiveStorage", "Im5vIHB1cnBvc2Ui--e731d4394a5529e3d27f6226ed3fe612cf01c1e1", NULL, "2026-01-01T12:00:00.000Z", true, "\"no purpose\""},
    {"valid something else x", "something else", "eyJfcmFpbHMiOnsiZGF0YSI6eyJiIjoxLCJhIjpbIlx1MDAzY1x1MDAyNlx1MDAzZSJdfSwicHVyIjoieCJ9fQ==--7ff86fef5fdbb102ede55845c3d0fb825b5672c5", "x", "2026-01-01T12:00:00.000Z", true, "{\"b\":1,\"a\":[\"\\u003c\\u0026\\u003e\"]}"},
    {"valid ActiveStorage blob_id", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--c252dc1b14dd0e8cd599eb40203378880bafed1f", "blob_id", "2026-01-01T12:00:00.000Z", true, "42"},
    {"wrong purpose", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--c252dc1b14dd0e8cd599eb40203378880bafed1f", "blob_key", "2026-01-01T12:00:00.000Z", false, NULL},
    {"wrong verifier name", "ActionText", "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--c252dc1b14dd0e8cd599eb40203378880bafed1f", "blob_id", "2026-01-01T12:00:00.000Z", false, NULL},
    {"expired", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJ4dGFwampjaml1ZHJsazN0bXd5amdwdW9iYWJkIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwiYVx1MDAyNmIucG5nXCI7IGZpbGVuYW1lKj1VVEYtOCcnYSUyNmIucG5nIiwiY29udGVudF90eXBlIjoiaW1hZ2UvcG5nIiwic2VydmljZV9uYW1lIjoibG9jYWwifSwiZXhwIjoiMjAyNi0wMS0wMVQxMjowNTowMC4wMDBaIiwicHVyIjoiYmxvYl9rZXkifX0=--764195902735b3201f5cf6129ff3b5089150e3e1", "blob_key", "2026-01-01T12:05:00.000Z", false, NULL},
    {"before expiry", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJ4dGFwampjaml1ZHJsazN0bXd5amdwdW9iYWJkIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwiYVx1MDAyNmIucG5nXCI7IGZpbGVuYW1lKj1VVEYtOCcnYSUyNmIucG5nIiwiY29udGVudF90eXBlIjoiaW1hZ2UvcG5nIiwic2VydmljZV9uYW1lIjoibG9jYWwifSwiZXhwIjoiMjAyNi0wMS0wMVQxMjowNTowMC4wMDBaIiwicHVyIjoiYmxvYl9rZXkifX0=--764195902735b3201f5cf6129ff3b5089150e3e1", "blob_key", "2026-01-01T12:04:00.000Z", true, "{\"key\":\"xtapjjcjiudrlk3tmwyjgpuobabd\",\"disposition\":\"inline; filename=\\\"a\\u0026b.png\\\"; filename*=UTF-8''a%26b.png\",\"content_type\":\"image/png\",\"service_name\":\"local\"}"},
    {"tampered", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--c252dc1b14dd0e8cd599eb40203378880bafed10", "blob_id", "2026-01-01T12:00:00.000Z", false, NULL},
    {"rotated secret", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--2bc1680ef971c93f5c69812ace5660de2c1278f4", "blob_id", "2026-01-01T12:00:00.000Z", false, NULL},
    {"url-safe encoding", "ActiveStorage", "eyJfcmFpbHMiOnsiZGF0YSI6Inh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4P1x1MDAzZSIsInB1ciI6InAifX0--d0d09cdae8153ac9eed98a685e120a2cd785e1a4", "p", "2026-01-01T12:00:00.000Z", true, "\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?\\u003e\""},
};
#define AUTH_VEC_APP_VERIFY_LEN (sizeof AUTH_VEC_APP_VERIFY / sizeof AUTH_VEC_APP_VERIFY[0])

#define AUTH_VEC_PASSWORD_COST 12
#define AUTH_VEC_SEEDED_DIGEST "$2a$12$kDVPfUd.VKsV9HzG8RHRFu0fyaW7gije1Krza2.A0J5S8XEcOQT4S"
typedef struct { const char *password; const char *digest; bool expected; } auth_vec_password_check;
static const auth_vec_password_check AUTH_VEC_PASSWORD_CHECKS[] = {
    {"secret123456", "$2a$12$I/2qP3ixlNN..JU2dXSN0umG7/Folk3aUaqgSHn/Rl0G82O9WYk66", true},
    {"p\303\244ssw\303\266rd \342\230\203", "$2a$12$I/2qP3ixlNN..JU2dXSN0umG7/Folk3aUaqgSHn/Rl0G82O9WYk66", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$I/2qP3ixlNN..JU2dXSN0umG7/Folk3aUaqgSHn/Rl0G82O9WYk66", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaignored", "$2a$12$I/2qP3ixlNN..JU2dXSN0umG7/Folk3aUaqgSHn/Rl0G82O9WYk66", false},
    {"x", "$2a$12$I/2qP3ixlNN..JU2dXSN0umG7/Folk3aUaqgSHn/Rl0G82O9WYk66", false},
    {"wrong", "$2a$12$I/2qP3ixlNN..JU2dXSN0umG7/Folk3aUaqgSHn/Rl0G82O9WYk66", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$I/2qP3ixlNN..JU2dXSN0umG7/Folk3aUaqgSHn/Rl0G82O9WYk66", false},
    {"secret123456 ", "$2a$12$I/2qP3ixlNN..JU2dXSN0umG7/Folk3aUaqgSHn/Rl0G82O9WYk66", false},
    {"secret123456", "$2a$12$kolfXguIoTYueHR5JN6QAeV84/81BRcUbA.dz4fVMiqp5RUtos1I6", false},
    {"p\303\244ssw\303\266rd \342\230\203", "$2a$12$kolfXguIoTYueHR5JN6QAeV84/81BRcUbA.dz4fVMiqp5RUtos1I6", true},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$kolfXguIoTYueHR5JN6QAeV84/81BRcUbA.dz4fVMiqp5RUtos1I6", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaignored", "$2a$12$kolfXguIoTYueHR5JN6QAeV84/81BRcUbA.dz4fVMiqp5RUtos1I6", false},
    {"x", "$2a$12$kolfXguIoTYueHR5JN6QAeV84/81BRcUbA.dz4fVMiqp5RUtos1I6", false},
    {"wrong", "$2a$12$kolfXguIoTYueHR5JN6QAeV84/81BRcUbA.dz4fVMiqp5RUtos1I6", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$kolfXguIoTYueHR5JN6QAeV84/81BRcUbA.dz4fVMiqp5RUtos1I6", false},
    {"secret123456 ", "$2a$12$kolfXguIoTYueHR5JN6QAeV84/81BRcUbA.dz4fVMiqp5RUtos1I6", false},
    {"secret123456", "$2a$12$TZrwCKzycdLOZ2HeWOMW1OYHE8nrAWHoOY05FWLQ6N38GSUKn4DMW", false},
    {"p\303\244ssw\303\266rd \342\230\203", "$2a$12$TZrwCKzycdLOZ2HeWOMW1OYHE8nrAWHoOY05FWLQ6N38GSUKn4DMW", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$TZrwCKzycdLOZ2HeWOMW1OYHE8nrAWHoOY05FWLQ6N38GSUKn4DMW", true},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaignored", "$2a$12$TZrwCKzycdLOZ2HeWOMW1OYHE8nrAWHoOY05FWLQ6N38GSUKn4DMW", true},
    {"x", "$2a$12$TZrwCKzycdLOZ2HeWOMW1OYHE8nrAWHoOY05FWLQ6N38GSUKn4DMW", false},
    {"wrong", "$2a$12$TZrwCKzycdLOZ2HeWOMW1OYHE8nrAWHoOY05FWLQ6N38GSUKn4DMW", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$TZrwCKzycdLOZ2HeWOMW1OYHE8nrAWHoOY05FWLQ6N38GSUKn4DMW", false},
    {"secret123456 ", "$2a$12$TZrwCKzycdLOZ2HeWOMW1OYHE8nrAWHoOY05FWLQ6N38GSUKn4DMW", false},
    {"secret123456", "$2a$12$7ymzJw79L3lWy0kZKREoMOyowLTl015hCs3J1dIPjo8LLPxayN5f6", false},
    {"p\303\244ssw\303\266rd \342\230\203", "$2a$12$7ymzJw79L3lWy0kZKREoMOyowLTl015hCs3J1dIPjo8LLPxayN5f6", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$7ymzJw79L3lWy0kZKREoMOyowLTl015hCs3J1dIPjo8LLPxayN5f6", true},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaignored", "$2a$12$7ymzJw79L3lWy0kZKREoMOyowLTl015hCs3J1dIPjo8LLPxayN5f6", true},
    {"x", "$2a$12$7ymzJw79L3lWy0kZKREoMOyowLTl015hCs3J1dIPjo8LLPxayN5f6", false},
    {"wrong", "$2a$12$7ymzJw79L3lWy0kZKREoMOyowLTl015hCs3J1dIPjo8LLPxayN5f6", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$7ymzJw79L3lWy0kZKREoMOyowLTl015hCs3J1dIPjo8LLPxayN5f6", false},
    {"secret123456 ", "$2a$12$7ymzJw79L3lWy0kZKREoMOyowLTl015hCs3J1dIPjo8LLPxayN5f6", false},
    {"secret123456", "$2a$12$Oi.yyHOhd2c.0yUMCk2FuOwFrMD3jDDjMTjQLrLmLprRMpX0eS296", false},
    {"p\303\244ssw\303\266rd \342\230\203", "$2a$12$Oi.yyHOhd2c.0yUMCk2FuOwFrMD3jDDjMTjQLrLmLprRMpX0eS296", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$Oi.yyHOhd2c.0yUMCk2FuOwFrMD3jDDjMTjQLrLmLprRMpX0eS296", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaignored", "$2a$12$Oi.yyHOhd2c.0yUMCk2FuOwFrMD3jDDjMTjQLrLmLprRMpX0eS296", false},
    {"x", "$2a$12$Oi.yyHOhd2c.0yUMCk2FuOwFrMD3jDDjMTjQLrLmLprRMpX0eS296", true},
    {"wrong", "$2a$12$Oi.yyHOhd2c.0yUMCk2FuOwFrMD3jDDjMTjQLrLmLprRMpX0eS296", false},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "$2a$12$Oi.yyHOhd2c.0yUMCk2FuOwFrMD3jDDjMTjQLrLmLprRMpX0eS296", false},
    {"secret123456 ", "$2a$12$Oi.yyHOhd2c.0yUMCk2FuOwFrMD3jDDjMTjQLrLmLprRMpX0eS296", false},
};
#define AUTH_VEC_PASSWORD_CHECKS_LEN (sizeof AUTH_VEC_PASSWORD_CHECKS / sizeof AUTH_VEC_PASSWORD_CHECKS[0])

typedef struct { const char *model_name; const char *id; const char *gid; const char *param; } auth_vec_gid;
static const auth_vec_gid AUTH_VEC_GIDS[] = {
    {"User", "1", "gid://campfire/User/1", "Z2lkOi8vY2FtcGZpcmUvVXNlci8x"},
    {"User", "2", "gid://campfire/User/2", "Z2lkOi8vY2FtcGZpcmUvVXNlci8y"},
    {"Rooms::Open", "1", "gid://campfire/Rooms::Open/1", "Z2lkOi8vY2FtcGZpcmUvUm9vbXM6Ok9wZW4vMQ"},
    {"Account", "1", "gid://campfire/Account/1", "Z2lkOi8vY2FtcGZpcmUvQWNjb3VudC8x"},
};
#define AUTH_VEC_GIDS_LEN (sizeof AUTH_VEC_GIDS / sizeof AUTH_VEC_GIDS[0])

#endif /* CF_TESTS_AUTH_VECTORS_H */
