/* Generated by tests/db/gen_schema_sql.py from the checked-in contract.
 * Do not edit this file by hand; regenerate and commit the result:
 *
 *     python3 tests/db/gen_schema_sql.py
 *
 * Provenance
 * ----------
 * Source:      docs/devel/implementation/contracts/schema.sql
 * Source sha256: 9dacc4bda60e2a12e583454989dc41c9640c99c0ef41a29640a09e9e984dadc6
 * Source bytes:  7111
 * Generated:   2026-10-04 by task D01 (db-core) from the contract revision
 *               in this checkout.
 *
 * CF_DB_SCHEMA_SQL is the contract byte for byte, including its final
 * `PRAGMA user_version = 1;`.  src/db/schema.c executes it inside one
 * BEGIN IMMEDIATE transaction when it creates a fresh database.
 */
#ifndef CF_DB_SCHEMA_SQL_H
#define CF_DB_SCHEMA_SQL_H

#define CF_DB_SCHEMA_SQL_SOURCE "docs/devel/implementation/contracts/schema.sql"
#define CF_DB_SCHEMA_SQL_SHA256 "9dacc4bda60e2a12e583454989dc41c9640c99c0ef41a29640a09e9e984dadc6"
#define CF_DB_SCHEMA_SQL_BYTES 7111

#define CF_DB_SCHEMA_SQL \
    "-- Specification artifact: fresh database only. Source: pinned Rust schema.sql,\n" \
    "-- Rails bookkeeping removed; message index and application user_version added.\n" \
    "CREATE TABLE \"accounts\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"created_at\" datetime(6) NOT NULL, \"custom_styles\" text, \"join_code\" varchar NOT NULL, \"name\" varchar NOT NULL, \"settings\" json, \"singleton_guard\" integer DEFAULT 0 NOT NULL, \"updated_at\" datetime(6) NOT NULL);\n" \
    "CREATE UNIQUE INDEX \"index_accounts_on_singleton_guard\" ON \"accounts\" (\"singleton_guard\");\n" \
    "CREATE TABLE \"action_text_rich_texts\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"body\" text, \"created_at\" datetime(6) NOT NULL, \"name\" varchar NOT NULL, \"record_id\" bigint NOT NULL, \"record_type\" varchar NOT NULL, \"updated_at\" datetime(6) NOT NULL);\n" \
    "CREATE UNIQUE INDEX \"index_action_text_rich_texts_uniqueness\" ON \"action_text_rich_texts\" (\"record_type\", \"record_id\", \"name\");\n" \
    "CREATE TABLE \"active_storage_blobs\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"byte_size\" bigint NOT NULL, \"checksum\" varchar, \"content_type\" varchar, \"created_at\" datetime(6) NOT NULL, \"filename\" varchar NOT NULL, \"key\" varchar NOT NULL, \"metadata\" text, \"service_name\" varchar NOT NULL);\n" \
    "CREATE UNIQUE INDEX \"index_active_storage_blobs_on_key\" ON \"active_storage_blobs\" (\"key\");\n" \
    "CREATE TABLE \"memberships\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"connected_at\" datetime(6), \"connections\" integer DEFAULT 0 NOT NULL, \"created_at\" datetime(6) NOT NULL, \"involvement\" varchar DEFAULT 'mentions', \"room_id\" integer NOT NULL, \"unread_at\" datetime(6), \"updated_at\" datetime(6) NOT NULL, \"user_id\" integer NOT NULL);\n" \
    "CREATE INDEX \"index_memberships_on_room_id_and_created_at\" ON \"memberships\" (\"room_id\", \"created_at\");\n" \
    "CREATE UNIQUE INDEX \"index_memberships_on_room_id_and_user_id\" ON \"memberships\" (\"room_id\", \"user_id\");\n" \
    "CREATE INDEX \"index_memberships_on_room_id\" ON \"memberships\" (\"room_id\");\n" \
    "CREATE INDEX \"index_memberships_on_user_id\" ON \"memberships\" (\"user_id\");\n" \
    "CREATE TABLE \"rooms\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"created_at\" datetime(6) NOT NULL, \"creator_id\" bigint NOT NULL, \"name\" varchar, \"type\" varchar NOT NULL, \"updated_at\" datetime(6) NOT NULL);\n" \
    "CREATE TABLE \"users\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"bio\" text, \"bot_token\" varchar, \"created_at\" datetime(6) NOT NULL, \"email_address\" varchar, \"name\" varchar NOT NULL, \"password_digest\" varchar, \"role\" integer DEFAULT 0 NOT NULL, \"status\" integer DEFAULT 0 NOT NULL, \"updated_at\" datetime(6) NOT NULL);\n" \
    "CREATE UNIQUE INDEX \"index_users_on_bot_token\" ON \"users\" (\"bot_token\");\n" \
    "CREATE UNIQUE INDEX \"index_users_on_email_address\" ON \"users\" (\"email_address\");\n" \
    "CREATE TABLE \"active_storage_attachments\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"blob_id\" bigint NOT NULL, \"created_at\" datetime(6) NOT NULL, \"name\" varchar NOT NULL, \"record_id\" bigint NOT NULL, \"record_type\" varchar NOT NULL, CONSTRAINT \"fk_rails_c3b3935057\"\n" \
    "FOREIGN KEY (\"blob_id\")\n" \
    "  REFERENCES \"active_storage_blobs\" (\"id\")\n" \
    ");\n" \
    "CREATE INDEX \"index_active_storage_attachments_on_blob_id\" ON \"active_storage_attachments\" (\"blob_id\");\n" \
    "CREATE UNIQUE INDEX \"index_active_storage_attachments_uniqueness\" ON \"active_storage_attachments\" (\"record_type\", \"record_id\", \"name\", \"blob_id\");\n" \
    "CREATE TABLE \"active_storage_variant_records\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"blob_id\" bigint NOT NULL, \"variation_digest\" varchar NOT NULL, CONSTRAINT \"fk_rails_993965df05\"\n" \
    "FOREIGN KEY (\"blob_id\")\n" \
    "  REFERENCES \"active_storage_blobs\" (\"id\")\n" \
    ");\n" \
    "CREATE UNIQUE INDEX \"index_active_storage_variant_records_uniqueness\" ON \"active_storage_variant_records\" (\"blob_id\", \"variation_digest\");\n" \
    "CREATE TABLE \"bans\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"created_at\" datetime(6) NOT NULL, \"ip_address\" varchar NOT NULL, \"updated_at\" datetime(6) NOT NULL, \"user_id\" integer NOT NULL, CONSTRAINT \"fk_rails_070022cd76\"\n" \
    "FOREIGN KEY (\"user_id\")\n" \
    "  REFERENCES \"users\" (\"id\")\n" \
    ");\n" \
    "CREATE INDEX \"index_bans_on_ip_address\" ON \"bans\" (\"ip_address\");\n" \
    "CREATE INDEX \"index_bans_on_user_id\" ON \"bans\" (\"user_id\");\n" \
    "CREATE TABLE \"boosts\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"booster_id\" integer NOT NULL, \"content\" varchar(16) NOT NULL, \"created_at\" datetime(6) NOT NULL, \"message_id\" integer NOT NULL, \"updated_at\" datetime(6) NOT NULL, CONSTRAINT \"fk_rails_3539c52d73\"\n" \
    "FOREIGN KEY (\"message_id\")\n" \
    "  REFERENCES \"messages\" (\"id\")\n" \
    ");\n" \
    "CREATE INDEX \"index_boosts_on_booster_id\" ON \"boosts\" (\"booster_id\");\n" \
    "CREATE INDEX \"index_boosts_on_message_id\" ON \"boosts\" (\"message_id\");\n" \
    "CREATE TABLE \"messages\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"client_message_id\" varchar NOT NULL, \"created_at\" datetime(6) NOT NULL, \"creator_id\" integer NOT NULL, \"room_id\" integer NOT NULL, \"updated_at\" datetime(6) NOT NULL, CONSTRAINT \"fk_rails_a8db0fb63a\"\n" \
    "FOREIGN KEY (\"room_id\")\n" \
    "  REFERENCES \"rooms\" (\"id\")\n" \
    ", CONSTRAINT \"fk_rails_761a2f12b3\"\n" \
    "FOREIGN KEY (\"creator_id\")\n" \
    "  REFERENCES \"users\" (\"id\")\n" \
    ");\n" \
    "CREATE INDEX \"index_messages_on_creator_id\" ON \"messages\" (\"creator_id\");\n" \
    "CREATE INDEX \"index_messages_on_room_id\" ON \"messages\" (\"room_id\");\n" \
    "CREATE TABLE \"push_subscriptions\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"auth_key\" varchar, \"created_at\" datetime(6) NOT NULL, \"endpoint\" varchar, \"p256dh_key\" varchar, \"updated_at\" datetime(6) NOT NULL, \"user_agent\" varchar, \"user_id\" integer NOT NULL, CONSTRAINT \"fk_rails_43d43720fc\"\n" \
    "FOREIGN KEY (\"user_id\")\n" \
    "  REFERENCES \"users\" (\"id\")\n" \
    ");\n" \
    "CREATE INDEX \"idx_on_endpoint_p256dh_key_auth_key_7553014576\" ON \"push_subscriptions\" (\"endpoint\", \"p256dh_key\", \"auth_key\");\n" \
    "CREATE INDEX \"index_push_subscriptions_on_user_id\" ON \"push_subscriptions\" (\"user_id\");\n" \
    "CREATE TABLE \"searches\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"created_at\" datetime(6) NOT NULL, \"query\" varchar NOT NULL, \"updated_at\" datetime(6) NOT NULL, \"user_id\" integer NOT NULL, CONSTRAINT \"fk_rails_e192b86393\"\n" \
    "FOREIGN KEY (\"user_id\")\n" \
    "  REFERENCES \"users\" (\"id\")\n" \
    ");\n" \
    "CREATE INDEX \"index_searches_on_user_id\" ON \"searches\" (\"user_id\");\n" \
    "CREATE TABLE \"sessions\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"created_at\" datetime(6) NOT NULL, \"ip_address\" varchar, \"last_active_at\" datetime(6) NOT NULL, \"token\" varchar NOT NULL, \"updated_at\" datetime(6) NOT NULL, \"user_agent\" varchar, \"user_id\" integer NOT NULL, CONSTRAINT \"fk_rails_758836b4f0\"\n" \
    "FOREIGN KEY (\"user_id\")\n" \
    "  REFERENCES \"users\" (\"id\")\n" \
    ");\n" \
    "CREATE UNIQUE INDEX \"index_sessions_on_token\" ON \"sessions\" (\"token\");\n" \
    "CREATE INDEX \"index_sessions_on_user_id\" ON \"sessions\" (\"user_id\");\n" \
    "CREATE TABLE \"webhooks\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"created_at\" datetime(6) NOT NULL, \"updated_at\" datetime(6) NOT NULL, \"url\" varchar, \"user_id\" integer NOT NULL, CONSTRAINT \"fk_rails_51bf96d3bc\"\n" \
    "FOREIGN KEY (\"user_id\")\n" \
    "  REFERENCES \"users\" (\"id\")\n" \
    ");\n" \
    "CREATE INDEX \"index_webhooks_on_user_id\" ON \"webhooks\" (\"user_id\");\n" \
    "CREATE VIRTUAL TABLE message_search_index USING fts5 (body, tokenize=porter);\n" \
    "CREATE INDEX \"index_messages_on_room_id_and_created_at\" ON \"messages\" (\"room_id\", \"created_at\");\n" \
    "PRAGMA user_version = 1;\n"

#endif /* CF_DB_SCHEMA_SQL_H */
