#!/usr/bin/env python3
"""Generate tests/auth/vectors.h from the pinned current-format fixtures.

Inputs (read-only):
  - tests/fixtures/vectors/rails_compat.json
  - tests/fixtures/MANIFEST.json (its `selection.selected` list is the
    current-format selection; legacy/Marshal vectors are excluded there)

Output: tests/auth/vectors.h, a C header of static tables.  Regenerating is a
reviewed source change: rerun this script and commit both files.  The test
binary never reads JSON at run time, so a missing fixture fails at build time
rather than passing silently.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
FIXTURE = os.path.join(ROOT, "tests", "fixtures", "vectors", "rails_compat.json")
MANIFEST = os.path.join(ROOT, "tests", "fixtures", "MANIFEST.json")
OUT = os.path.join(ROOT, "tests", "auth", "vectors.h")


def cstr(value):
    if value is None:
        return "NULL"
    out = []
    for byte in value.encode("utf-8"):
        ch = chr(byte)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif 0x20 <= byte < 0x7F:
            out.append(ch)
        else:
            # octal: always three digits, so a following hex digit cannot be
            # swallowed by the escape
            out.append("\\%03o" % byte)
    text = '"' + "".join(out) + '"'
    return text


def json_text(value):
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=False)


def selection(fixture_name):
    manifest = json.load(open(MANIFEST, encoding="utf-8"))
    for entry in manifest["entries"]:
        if entry["fixture"] == fixture_name:
            selected = entry["selection"]["selected"]
            picks = {}
            for item in selected:
                picks.setdefault(item["section"], set()).add(item["index"])
            return picks
    raise SystemExit("fixture not in manifest: " + fixture_name)


def selected(data, picks, section):
    out = []
    for index, case in enumerate(data):
        if index in picks.get(section, set()):
            out.append(case)
    return out


def gid_parse(text):
    if text is None:
        return None
    if text.startswith("gid://"):
        rest = text[len("gid://"):].split("?", 1)[0]
        if "/" not in rest:
            return None
        app, path = rest.split("/", 1)
        if "/" not in path:
            return None
        model, ident = path.split("/", 1)
        if not app or not model or not ident:
            return None
        return "gid://%s/%s/%s" % (app, model, ident)
    # GlobalID::from_param: URL-safe base64 of the gid URI
    import base64
    pad = "=" * ((4 - len(text) % 4) % 4)
    try:
        decoded = base64.urlsafe_b64decode(text + pad).decode("utf-8")
    except Exception:
        return None
    return gid_parse(decoded)


def main():
    data = json.load(open(FIXTURE, encoding="utf-8"))
    picks = selection("tests/fixtures/vectors/rails_compat.json")
    lines = []
    lines.append("/* tests/auth/vectors.h — generated by tests/auth/tools/generate_vectors.py.")
    lines.append(" * Source: tests/fixtures/vectors/rails_compat.json (current-format selection only;")
    lines.append(" * legacy/Marshal vectors are excluded by the fixture manifest, D-C01).")
    lines.append(" * Do not edit by hand: rerun the generator. */")
    lines.append("#ifndef CF_TESTS_AUTH_VECTORS_H")
    lines.append("#define CF_TESTS_AUTH_VECTORS_H")
    lines.append("")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define AUTH_VEC_SECRET_KEY_BASE " + cstr(data["secret_key_base"]))
    lines.append("#define AUTH_VEC_NOW " + cstr(data["now"]))
    lines.append("")

    # key generator
    lines.append("typedef struct { const char *salt; unsigned length; const char *key_hex; } auth_vec_key;")
    lines.append("static const auth_vec_key AUTH_VEC_KEYS[] = {")
    for case in data["key_generator"]:
        lines.append("    {%s, %d, %s}," % (cstr(case["salt"]), case["length"], cstr(case["key_hex"])))
    lines.append("};")
    lines.append("#define AUTH_VEC_KEYS_LEN (sizeof AUTH_VEC_KEYS / sizeof AUTH_VEC_KEYS[0])")
    lines.append("")

    # signed cookies
    lines.append("typedef struct { const char *name; const char *value; const char *expires_at; const char *raw; const char *set_cookie; } auth_vec_signed_gen;")
    lines.append("static const auth_vec_signed_gen AUTH_VEC_SIGNED_GEN[] = {")
    for case in data["signed_cookies"]["generate"]:
        lines.append("    {%s, %s, %s, %s, %s}," % (
            cstr(case["name"]), cstr(case["value"]),
            cstr(case.get("expires_at")), cstr(case["raw"]), cstr(case.get("set_cookie"))))
    lines.append("};")
    lines.append("#define AUTH_VEC_SIGNED_GEN_LEN (sizeof AUTH_VEC_SIGNED_GEN / sizeof AUTH_VEC_SIGNED_GEN[0])")
    lines.append("")
    lines.append("typedef struct { const char *case_name; const char *name; const char *raw; const char *now; bool has_expected; const char *expected; } auth_vec_cookie_verify;")
    lines.append("static const auth_vec_cookie_verify AUTH_VEC_SIGNED_VERIFY[] = {")
    for case in selected(data["signed_cookies"]["verify"], picks, "signed_cookies.verify"):
        expected = case.get("expected")
        if isinstance(expected, str):
            lines.append("    {%s, %s, %s, %s, true, %s}," % (
                cstr(case["case"]), cstr(case["name"]), cstr(case["raw"]),
                cstr(case.get("now", data["now"])), cstr(expected)))
        else:
            lines.append("    {%s, %s, %s, %s, false, NULL}," % (
                cstr(case["case"]), cstr(case["name"]), cstr(case["raw"]),
                cstr(case.get("now", data["now"]))))
    lines.append("};")
    lines.append("#define AUTH_VEC_SIGNED_VERIFY_LEN (sizeof AUTH_VEC_SIGNED_VERIFY / sizeof AUTH_VEC_SIGNED_VERIFY[0])")
    lines.append("")

    # encrypted cookies
    lines.append("typedef struct { const char *name; const char *value_json; const char *expires_at; } auth_vec_encrypted_gen;")
    lines.append("static const auth_vec_encrypted_gen AUTH_VEC_ENCRYPTED_GEN[] = {")
    for case in data["encrypted_cookies"]["generate"]:
        lines.append("    {%s, %s, %s}," % (
            cstr(case["name"]), cstr(json_text(case["value"])), cstr(case.get("expires_at"))))
    lines.append("};")
    lines.append("#define AUTH_VEC_ENCRYPTED_GEN_LEN (sizeof AUTH_VEC_ENCRYPTED_GEN / sizeof AUTH_VEC_ENCRYPTED_GEN[0])")
    lines.append("")
    lines.append("typedef struct { const char *case_name; const char *name; const char *raw; const char *now; bool has_expected; const char *expected_json; } auth_vec_encrypted_verify;")
    lines.append("static const auth_vec_encrypted_verify AUTH_VEC_ENCRYPTED_VERIFY[] = {")
    for case in selected(data["encrypted_cookies"]["verify"], picks, "encrypted_cookies.verify"):
        expected = case.get("expected")
        if expected is None:
            lines.append("    {%s, %s, %s, %s, false, NULL}," % (
                cstr(case["case"]), cstr(case["name"]), cstr(case["raw"]),
                cstr(case.get("now", data["now"]))))
        else:
            lines.append("    {%s, %s, %s, %s, true, %s}," % (
                cstr(case["case"]), cstr(case["name"]), cstr(case["raw"]),
                cstr(case.get("now", data["now"])), cstr(json_text(expected))))
    lines.append("};")
    lines.append("#define AUTH_VEC_ENCRYPTED_VERIFY_LEN (sizeof AUTH_VEC_ENCRYPTED_VERIFY / sizeof AUTH_VEC_ENCRYPTED_VERIFY[0])")
    lines.append("")

    # signed ids
    lines.append("typedef struct { const char *model; int64_t id; const char *purpose; const char *expires_at; const char *signed_id; } auth_vec_sid_gen;")
    lines.append("static const auth_vec_sid_gen AUTH_VEC_SID_GEN[] = {")
    for case in data["signed_ids"]["generate"]:
        lines.append("    {%s, %d, %s, %s, %s}," % (
            cstr(case["model"]), case["id"], cstr(case.get("purpose")),
            cstr(case.get("expires_at")), cstr(case["signed_id"])))
    lines.append("};")
    lines.append("#define AUTH_VEC_SID_GEN_LEN (sizeof AUTH_VEC_SID_GEN / sizeof AUTH_VEC_SID_GEN[0])")
    lines.append("")
    lines.append("typedef struct { const char *case_name; const char *model; const char *signed_id; const char *purpose; const char *now; bool has_expected; int64_t expected; } auth_vec_sid_verify;")
    lines.append("static const auth_vec_sid_verify AUTH_VEC_SID_VERIFY[] = {")
    for case in selected(data["signed_ids"]["verify"], picks, "signed_ids.verify"):
        expected = case.get("expected")
        if isinstance(expected, str):
            expected = int(expected)
        if expected is None:
            lines.append("    {%s, %s, %s, %s, %s, false, 0}," % (
                cstr(case["case"]), cstr(case["model"]), cstr(case["signed_id"]),
                cstr(case.get("purpose")), cstr(case.get("now", data["now"]))))
        else:
            lines.append("    {%s, %s, %s, %s, %s, true, %d}," % (
                cstr(case["case"]), cstr(case["model"]), cstr(case["signed_id"]),
                cstr(case.get("purpose")), cstr(case.get("now", data["now"])), expected))
    lines.append("};")
    lines.append("#define AUTH_VEC_SID_VERIFY_LEN (sizeof AUTH_VEC_SID_VERIFY / sizeof AUTH_VEC_SID_VERIFY[0])")
    lines.append("")

    # sgids
    lines.append("typedef struct { const char *gid; const char *data; const char *purpose; const char *expires_at; const char *sgid; } auth_vec_sgid_gen;")
    lines.append("static const auth_vec_sgid_gen AUTH_VEC_SGID_GEN[] = {")
    for case in data["sgids"]["generate"]:
        lines.append("    {%s, %s, %s, %s, %s}," % (
            cstr(case["gid"]), cstr(case["data"]), cstr(case["purpose"]),
            cstr(case.get("expires_at")), cstr(case["sgid"])))
    lines.append("};")
    lines.append("#define AUTH_VEC_SGID_GEN_LEN (sizeof AUTH_VEC_SGID_GEN / sizeof AUTH_VEC_SGID_GEN[0])")
    lines.append("")
    lines.append("typedef struct { const char *case_name; const char *sgid; const char *purpose; const char *now; bool has_expected; const char *expected_gid; } auth_vec_sgid_verify;")
    lines.append("static const auth_vec_sgid_verify AUTH_VEC_SGID_VERIFY[] = {")
    for case in selected(data["sgids"]["verify"], picks, "sgids.verify"):
        expected = gid_parse(case.get("expected"))
        if expected is None:
            lines.append("    {%s, %s, %s, %s, false, NULL}," % (
                cstr(case["case"]), cstr(case["sgid"]), cstr(case["purpose"]),
                cstr(case.get("now", data["now"]))))
        else:
            lines.append("    {%s, %s, %s, %s, true, %s}," % (
                cstr(case["case"]), cstr(case["sgid"]), cstr(case["purpose"]),
                cstr(case.get("now", data["now"])), cstr(expected)))
    lines.append("};")
    lines.append("#define AUTH_VEC_SGID_VERIFY_LEN (sizeof AUTH_VEC_SGID_VERIFY / sizeof AUTH_VEC_SGID_VERIFY[0])")
    lines.append("")

    # turbo
    lines.append("typedef struct { const char *parts[8]; size_t parts_len; const char *stream_name; const char *signed_name; } auth_vec_turbo_gen;")
    lines.append("static const auth_vec_turbo_gen AUTH_VEC_TURBO_GEN[] = {")
    for case in data["turbo_stream_names"]["generate"]:
        parts = case["parts"]
        assert len(parts) <= 8
        parts_c = ", ".join(cstr(p) for p in parts)
        lines.append("    {{%s}, %d, %s, %s}," % (
            parts_c, len(parts), cstr(case["stream_name"]), cstr(case["signed"])))
    lines.append("};")
    lines.append("#define AUTH_VEC_TURBO_GEN_LEN (sizeof AUTH_VEC_TURBO_GEN / sizeof AUTH_VEC_TURBO_GEN[0])")
    lines.append("")
    lines.append("typedef struct { const char *case_name; const char *signed_name; bool has_expected; const char *expected; } auth_vec_turbo_verify;")
    lines.append("static const auth_vec_turbo_verify AUTH_VEC_TURBO_VERIFY[] = {")
    for case in selected(data["turbo_stream_names"]["verify"], picks, "turbo_stream_names.verify"):
        expected = case.get("expected")
        if expected is None:
            lines.append("    {%s, %s, false, NULL}," % (
                cstr(case["case"]), cstr(case["signed"])))
        elif isinstance(expected, str):
            lines.append("    {%s, %s, true, %s}," % (
                cstr(case["case"]), cstr(case["signed"]), cstr(expected)))
        else:
            lines.append("    {%s, %s, true, %s}," % (
                cstr(case["case"]), cstr(case["signed"]), cstr(json_text(expected))))
    lines.append("};")
    lines.append("#define AUTH_VEC_TURBO_VERIFY_LEN (sizeof AUTH_VEC_TURBO_VERIFY / sizeof AUTH_VEC_TURBO_VERIFY[0])")
    lines.append("")

    # app verifiers
    lines.append("typedef struct { const char *name; const char *data_json; const char *purpose; const char *expires_at; const char *message; } auth_vec_app_gen;")
    lines.append("static const auth_vec_app_gen AUTH_VEC_APP_GEN[] = {")
    for case in data["app_verifiers"]["generate"]:
        lines.append("    {%s, %s, %s, %s, %s}," % (
            cstr(case["name"]), cstr(case["data_json"]), cstr(case.get("purpose")),
            cstr(case.get("expires_at")), cstr(case["message"])))
    lines.append("};")
    lines.append("#define AUTH_VEC_APP_GEN_LEN (sizeof AUTH_VEC_APP_GEN / sizeof AUTH_VEC_APP_GEN[0])")
    lines.append("")
    lines.append("typedef struct { const char *case_name; const char *name; const char *message; const char *purpose; const char *now; bool has_expected; const char *expected_json; } auth_vec_app_verify;")
    lines.append("static const auth_vec_app_verify AUTH_VEC_APP_VERIFY[] = {")
    for case in selected(data["app_verifiers"]["verify"], picks, "app_verifiers.verify"):
        expected = case.get("expected_json")
        if expected is None:
            lines.append("    {%s, %s, %s, %s, %s, false, NULL}," % (
                cstr(case["case"]), cstr(case["name"]), cstr(case["message"]),
                cstr(case.get("purpose")), cstr(case.get("now", data["now"]))))
        else:
            lines.append("    {%s, %s, %s, %s, %s, true, %s}," % (
                cstr(case["case"]), cstr(case["name"]), cstr(case["message"]),
                cstr(case.get("purpose")), cstr(case.get("now", data["now"])),
                cstr(expected)))
    lines.append("};")
    lines.append("#define AUTH_VEC_APP_VERIFY_LEN (sizeof AUTH_VEC_APP_VERIFY / sizeof AUTH_VEC_APP_VERIFY[0])")
    lines.append("")

    # passwords
    lines.append("#define AUTH_VEC_PASSWORD_COST %d" % data["passwords"]["cost"])
    lines.append("#define AUTH_VEC_SEEDED_DIGEST %s" % cstr(data["passwords"]["seeded_user_digest"]))
    lines.append("typedef struct { const char *password; const char *digest; bool expected; } auth_vec_password_check;")
    lines.append("static const auth_vec_password_check AUTH_VEC_PASSWORD_CHECKS[] = {")
    for case in data["passwords"]["checks"]:
        lines.append("    {%s, %s, %s}," % (
            cstr(case["password"]), cstr(case["digest"]),
            "true" if case["expected"] else "false"))
    lines.append("};")
    lines.append("#define AUTH_VEC_PASSWORD_CHECKS_LEN (sizeof AUTH_VEC_PASSWORD_CHECKS / sizeof AUTH_VEC_PASSWORD_CHECKS[0])")
    lines.append("")

    # global ids
    lines.append("typedef struct { const char *model_name; const char *id; const char *gid; const char *param; } auth_vec_gid;")
    lines.append("static const auth_vec_gid AUTH_VEC_GIDS[] = {")
    for case in data["global_ids"]:
        lines.append("    {%s, %s, %s, %s}," % (
            cstr(case["model_name"]), cstr(case["id"]), cstr(case["gid"]),
            cstr(case["param"])))
    lines.append("};")
    lines.append("#define AUTH_VEC_GIDS_LEN (sizeof AUTH_VEC_GIDS / sizeof AUTH_VEC_GIDS[0])")
    lines.append("")
    lines.append("#endif /* CF_TESTS_AUTH_VECTORS_H */")

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print("wrote", OUT, "lines", len(lines))


if __name__ == "__main__":
    sys.exit(main())
